using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ChatXdk
{
    /// <summary>
    /// The main X Chat encryption SDK.
    ///
    /// <para>Wraps the Rust <c>chat_xdk_core</c> library via P/Invoke and provides
    /// the operations exposed by the SDK:</para>
    /// <list type="bullet">
    ///   <item>Key generation and Juicebox-backed storage (<see cref="GenerateKeypairs"/>, <see cref="Setup"/>, <see cref="Unlock"/>)</item>
    ///   <item>Event decryption (<see cref="ExtractConversationKeys"/>, <see cref="DecryptEvents"/>, <see cref="DecryptEvent"/>)</item>
    ///   <item>Signed conversation-key changes (<see cref="PrepareConversationKeyChange"/>, <see cref="PrepareGroupCreate"/>, <see cref="PrepareGroupMembersChange"/>)</item>
    ///   <item>UTF-8 metadata encryption with the conversation key (<see cref="Encrypt"/>, <see cref="Decrypt"/>)</item>
    ///   <item>Message / reaction / reply encryption (<see cref="EncryptMessage"/>, etc.)</item>
    ///   <item>Media streaming encryption (<see cref="EncryptStream"/>, <see cref="DecryptStream"/>)</item>
    ///   <item>Stateless helpers on <see cref="ChatXdkUtilities"/> (base64/hex, MIME, image dimensions)</item>
    /// </list>
    ///
    /// <para>Always <see cref="Dispose"/> the instance when finished to release native resources.</para>
    ///
    /// <para>Not thread-safe: do not share one instance across threads without external
    /// synchronization. Mutating operations (<see cref="Setup"/>, <see cref="Unlock"/>,
    /// <see cref="Delete"/>, <see cref="ChangePin"/>, <see cref="UpdateConfig"/>,
    /// <see cref="SetRejectUnverified"/>,
    /// <see cref="SetIdentity"/>, <see cref="SetCacheKeys"/>, <see cref="SetSigningKeys"/>)
    /// must not race decrypt or any other call on the same instance.</para>
    /// </summary>
    /// <example>
    /// <code>
    /// using var chat = new Chat();
    /// chat.Unlock("2580", juiceboxConfigJson);
    /// chat.SetIdentity(myUserId, mySigningKeyVersion); // session identity, once
    /// chat.SetCacheKeys(true);                         // opt-in conversation-key cache
    /// chat.SetSigningKeys(participantSigningKeys);     // default verification keys
    ///
    /// // Decrypt incoming events (keys are cached from verified KeyChange events)
    /// var result = chat.DecryptEvents(eventsB64);
    /// var evt = chat.DecryptEvent(eventB64);
    /// Console.WriteLine(evt.GetProperty("type").GetString()); // "Message", "KeyChange", …
    ///
    /// // Send a message — identity and conversation key resolve from the session
    /// var payload = chat.EncryptMessage(new EncryptMessageParams(convId, "Hello from .NET!"));
    /// // The SDK generates the message id; read it back from payload.MessageId.
    /// // POST payload fields to the X API…
    /// </code>
    /// </example>
    public sealed unsafe class Chat : IDisposable
    {
        // Pointer to the native ChatHandle allocated by chat_xdk_new().
        // ChatHandle is generated by csbindgen at the ChatXdk namespace level.
        private ChatHandle* _handle;
        private bool _disposed;

        // Shared JSON options: ignore nulls on write. Property names are
        // snake_case via explicit [JsonPropertyName] attributes on each DTO,
        // not a naming policy here.
        private static readonly JsonSerializerOptions JsonOpts = new()
        {
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        };

        /// <summary>
        /// Create a new Chat SDK instance.
        /// </summary>
        /// <exception cref="InvalidOperationException">
        /// Thrown if the native library fails to initialise (e.g. missing shared library).
        /// </exception>
        public Chat()
        {
            _handle = NativeMethods.chat_xdk_new();
            if (_handle == null)
                throw new InvalidOperationException(
                    "chat_xdk_new() returned NULL — ensure the native library " +
                    "(chat_xdk_dotnet.dylib / .so / .dll) is on the library search path.");
        }

        /// <summary>
        /// Finalizer — ensures the native handle is freed even if <see cref="Dispose"/>
        /// is never called explicitly (e.g. the object is forgotten without <c>using</c>).
        /// An object becomes finalizable as soon as its last use passes — even while
        /// one of its methods is still executing native code — so every method that
        /// passes <c>_handle</c> across the P/Invoke boundary calls
        /// <see cref="GC.KeepAlive(object)"/> on <c>this</c> after the call, keeping
        /// this finalizer from freeing the handle mid-call.
        /// </summary>
        ~Chat() => Dispose(disposing: false);

        /// <inheritdoc/>
        public void Dispose()
        {
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            // Both the finalizer and Dispose() paths end here.
            // We only need to free the unmanaged handle; there are no managed resources.
            if (!_disposed)
            {
                _disposed = true;
                if (_handle != null)
                {
                    NativeMethods.chat_xdk_free(_handle);
                    _handle = null;
                }
            }
        }

        // Internal helpers

        private void ThrowIfDisposed()
        {
            if (_disposed) throw new ObjectDisposedException(nameof(Chat));
        }

        /// <summary>
        /// Consume a native <see cref="FfiResult"/>: free both pointers,
        /// throw <see cref="ChatXdkException"/> on error, return the data string on success.
        /// Returns an empty string for void-OK results.
        /// </summary>
        internal static string ConsumeResult(FfiResult result)
        {
            // Always marshal both strings before freeing — avoids a double-free
            // if the error branch short-circuits.
            string? data = result.data != null
                ? Marshal.PtrToStringUTF8((IntPtr)result.data)
                : null;
            string? error = result.error != null
                ? Marshal.PtrToStringUTF8((IntPtr)result.error)
                : null;

            if (result.data != null) NativeMethods.chat_xdk_free_string(result.data);
            if (result.error != null) NativeMethods.chat_xdk_free_string(result.error);

            if (error != null) throw new ChatXdkException(error);
            return data ?? "";
        }

        /// <summary>Encode <paramref name="s"/> as a null-terminated UTF-8 byte array.</summary>
        internal static byte[] Utf8Z(string s)
        {
            int len = Encoding.UTF8.GetByteCount(s);
            byte[] buf = new byte[len + 1]; // +1 for '\0'
            Encoding.UTF8.GetBytes(s, 0, s.Length, buf, 0);
            return buf; // buf[len] is already 0
        }

        /// <summary>
        /// Parse <c>{"keys":{...},"latest_version":...}</c> from extract/decrypt_events JSON.
        /// </summary>
        private static ConversationKeyBundle ParseConversationKeyBundle(JsonElement root)
        {
            var keysEl = root.GetProperty("keys");
            var keys = new Dictionary<string, byte[]>();
            foreach (var prop in keysEl.EnumerateObject())
                keys[prop.Name] = Convert.FromBase64String(prop.Value.GetString()!);

            string? latest = null;
            if (root.TryGetProperty("latest_version", out var lv) && lv.ValueKind == JsonValueKind.String)
                latest = lv.GetString();

            return new ConversationKeyBundle { Keys = keys, LatestVersion = latest };
        }

        // State

        /// <summary>True when both identity and signing keys are loaded in memory.</summary>
        public bool IsUnlocked
        {
            get
            {
                ThrowIfDisposed();
                bool unlocked = NativeMethods.chat_xdk_is_unlocked(_handle) == 1;
                GC.KeepAlive(this);
                return unlocked;
            }
        }

        /// <summary>True when the identity key is loaded (sufficient for decryption).</summary>
        public bool HasIdentityKey
        {
            get
            {
                ThrowIfDisposed();
                bool loaded = NativeMethods.chat_xdk_has_identity_key(_handle) == 1;
                GC.KeepAlive(this);
                return loaded;
            }
        }

        /// <summary>
        /// When <paramref name="reject"/> is true — the default — <see cref="DecryptEvent"/>
        /// throws <see cref="ChatXdkException"/> for any signed event whose signature cannot
        /// be verified (invalid, missing, or no matching signing key) instead of returning
        /// it with <c>verified: false</c>.
        /// </summary>
        public void SetRejectUnverified(bool reject)
        {
            ThrowIfDisposed();
            NativeMethods.chat_xdk_set_reject_unverified(_handle, reject ? 1 : 0);
            GC.KeepAlive(this);
        }

        /// <summary>
        /// Set the session identity: the owner's user id and signing-key version, used
        /// as the defaults wherever a params class' <c>SenderId</c> / <c>SigningKeyVersion</c>
        /// is left null. A resolved default and an explicitly passed value produce
        /// byte-identical signed output for the same logical inputs.
        /// </summary>
        public void SetIdentity(string userId, string signingKeyVersion)
        {
            ThrowIfDisposed();
            var user = Utf8Z(userId);
            var ver = Utf8Z(signingKeyVersion);
            fixed (byte* userPtr = user)
            fixed (byte* verPtr = ver)
                ConsumeResult(NativeMethods.chat_xdk_set_identity(_handle, userPtr, verPtr));
            GC.KeepAlive(this);
        }

        /// <summary>
        /// Enable or disable the conversation-key cache (off by default). While enabled,
        /// <see cref="DecryptEvents"/> caches, per conversation, the key whose key change
        /// carried a valid signature at the highest version seen, and the encrypt methods
        /// resolve a null <c>ConversationKey</c>/<c>ConversationKeyVersion</c> pair from it.
        /// Disabling clears the cache.
        /// </summary>
        public void SetCacheKeys(bool enabled)
        {
            ThrowIfDisposed();
            NativeMethods.chat_xdk_set_cache_keys(_handle, enabled ? 1 : 0);
            GC.KeepAlive(this);
        }

        /// <summary>
        /// Store signing keys to use when a decrypt call omits its <c>signingKeys</c>
        /// argument. Only this explicit call populates the store — a key carried inside
        /// an event is never trusted for verification. Each call replaces the previous set.
        /// </summary>
        public void SetSigningKeys(IReadOnlyList<SigningKeyEntry> keys)
        {
            ThrowIfDisposed();
            var json = JsonSerializer.Serialize(keys, JsonOpts);
            var jsonBytes = Utf8Z(json);
            fixed (byte* jsonPtr = jsonBytes)
                ConsumeResult(NativeMethods.chat_xdk_set_signing_keys(_handle, jsonPtr));
            GC.KeepAlive(this);
        }

        /// <summary>Clear all key material from memory without touching Juicebox.</summary>
        public void Lock()
        {
            ThrowIfDisposed();
            NativeMethods.chat_xdk_lock(_handle);
            GC.KeepAlive(this);
        }

        // Juicebox lifecycle

        /// <summary>
        /// Update the Juicebox configuration — call this whenever the X API
        /// issues fresh short-lived auth tokens.
        /// </summary>
        public void UpdateConfig(string configJson)
        {
            ThrowIfDisposed();
            var cfg = Utf8Z(configJson);
            fixed (byte* cfgPtr = cfg)
                ConsumeResult(NativeMethods.chat_xdk_update_config(_handle, cfgPtr));
            GC.KeepAlive(this);
        }

        /// <summary>
        /// Register the SDK's keys with Juicebox (first-time setup).
        /// Call <see cref="GenerateKeypairs"/> and POST the result to the X API first,
        /// then call this to persist the keys under the user's PIN.
        /// </summary>
        /// <param name="pin">User-chosen PIN.</param>
        /// <param name="configJson">Juicebox configuration JSON from the X API.</param>
        /// <returns>The user's public keys to upload to the X API.</returns>
        public PublicKeys Setup(string pin, string configJson)
        {
            ThrowIfDisposed();
            var pinBytes = Utf8Z(pin);
            var cfgBytes = Utf8Z(configJson);
            string json;
            fixed (byte* pinPtr = pinBytes)
            fixed (byte* cfgPtr = cfgBytes)
                json = ConsumeResult(NativeMethods.chat_xdk_setup(_handle, pinPtr, cfgPtr));
            GC.KeepAlive(this);
            return JsonSerializer.Deserialize<PublicKeys>(json, JsonOpts)!;
        }

        /// <summary>
        /// Recover keys from Juicebox and load them into memory.
        /// Call on every startup after the user enters their PIN.
        /// </summary>
        /// <param name="pin">The user's PIN.</param>
        /// <param name="configJson">Juicebox configuration JSON from the X API.</param>
        public void Unlock(string pin, string configJson)
        {
            ThrowIfDisposed();
            var pinBytes = Utf8Z(pin);
            var cfgBytes = Utf8Z(configJson);
            fixed (byte* pinPtr = pinBytes)
            fixed (byte* cfgPtr = cfgBytes)
                ConsumeResult(NativeMethods.chat_xdk_unlock(_handle, pinPtr, cfgPtr));
            GC.KeepAlive(this);
        }

        /// <summary>
        /// Delete the user's keys from Juicebox and lock the SDK.
        /// Warning: Irreversible — the user loses access to their encrypted message history.
        /// </summary>
        public void Delete()
        {
            ThrowIfDisposed();
            ConsumeResult(NativeMethods.chat_xdk_delete(_handle));
            GC.KeepAlive(this);
        }

        /// <summary>Re-register keys under a new PIN.</summary>
        public void ChangePin(string oldPin, string newPin)
        {
            ThrowIfDisposed();
            var oldBytes = Utf8Z(oldPin);
            var newBytes = Utf8Z(newPin);
            fixed (byte* oldPtr = oldBytes)
            fixed (byte* newPtr = newBytes)
                ConsumeResult(NativeMethods.chat_xdk_change_pin(_handle, oldPtr, newPtr));
            GC.KeepAlive(this);
        }

        // Key management

        /// <summary>
        /// Generate new identity + signing keypairs and return the registration payload.
        /// POST the payload to <c>POST /2/chat/keys</c> before calling <see cref="Setup"/>.
        /// </summary>
        public PublicKeyRegistrationPayload GenerateKeypairs()
        {
            ThrowIfDisposed();
            var json = ConsumeResult(NativeMethods.chat_xdk_generate_keypairs(_handle));
            GC.KeepAlive(this);
            return JsonSerializer.Deserialize<PublicKeyRegistrationPayload>(json, JsonOpts)!;
        }

        /// <summary>Get the user's current public keys (requires keys to be loaded).</summary>
        public PublicKeys GetPublicKeys()
        {
            ThrowIfDisposed();
            var json = ConsumeResult(NativeMethods.chat_xdk_get_public_keys(_handle));
            GC.KeepAlive(this);
            return JsonSerializer.Deserialize<PublicKeys>(json, JsonOpts)!;
        }

        /// <summary>
        /// Get the fingerprint of the loaded identity public key.
        /// Returns a URL-safe base64 SHA-256 of the SPKI-encoded key —
        /// suitable for out-of-band verification by the user.
        /// </summary>
        public string GetPublicKeyFingerprint()
        {
            ThrowIfDisposed();
            var fingerprint = ConsumeResult(NativeMethods.chat_xdk_get_public_key_fingerprint(_handle));
            GC.KeepAlive(this);
            return fingerprint;
        }

        /// <summary>
        /// Export private keys as raw bytes for a secure backup.
        /// Returns <see langword="null"/> if the SDK is locked.
        /// Warning: These are raw secret key bytes — store with extreme care.
        /// </summary>
        public byte[]? ExportKeys()
        {
            ThrowIfDisposed();
            // Mirrors core's export requirement: identity key present
            // (signing key optional, giving a 32-byte export).
            if (!HasIdentityKey) return null;
            var b64 = ConsumeResult(NativeMethods.chat_xdk_export_keys(_handle));
            GC.KeepAlive(this);
            if (string.IsNullOrEmpty(b64)) return null;
            return Convert.FromBase64String(b64);
        }

        /// <summary>
        /// Import private keys from a byte array produced by <see cref="ExportKeys"/>.
        /// Accepts 32 bytes (identity only) or 64 bytes (identity + signing).
        /// When <paramref name="version"/> is given, the public key version the keys
        /// were registered under is recorded as well, so participant-key filtering
        /// and the session signing-key version are set in one call.
        /// </summary>
        public void ImportKeys(byte[] keys, string? version = null)
        {
            ThrowIfDisposed();
            if (version != null)
            {
                var ver = Utf8Z(version);
                // A zero-length array pins to a null pointer on some CLRs; the
                // native side treats NULL + length 0 as an empty key blob.
                if (keys.Length == 0)
                {
                    fixed (byte* verPtr = ver)
                        ConsumeResult(NativeMethods.chat_xdk_import_keys_with_version(_handle, null, 0, verPtr));
                }
                else
                {
                    fixed (byte* keysPtr = keys)
                    fixed (byte* verPtr = ver)
                        ConsumeResult(NativeMethods.chat_xdk_import_keys_with_version(
                            _handle, keysPtr, (nuint)keys.Length, verPtr));
                }
                GC.KeepAlive(this);
                return;
            }
            var b64 = Convert.ToBase64String(keys);
            var b64Bytes = Utf8Z(b64);
            fixed (byte* b64Ptr = b64Bytes)
                ConsumeResult(NativeMethods.chat_xdk_import_keys(_handle, b64Ptr));
            GC.KeepAlive(this);
        }

        // Event decryption

        /// <summary>
        /// Extract and decrypt conversation keys from raw <c>KeyChange</c> event strings.
        /// </summary>
        /// <param name="events">
        /// Base64-encoded raw event strings received from the webhook.
        /// Pass only <c>KeyChange</c> events — other event types are ignored.
        /// </param>
        /// <returns>
        /// Decrypted keys and <see cref="ConversationKeyBundle.LatestVersion"/>.
        /// Pass <see cref="ConversationKeyBundle.Keys"/> (or the whole bundle) to <see cref="DecryptEvent"/>.
        /// </returns>
        public ConversationKeyBundle ExtractConversationKeys(IEnumerable<string> events)
        {
            ThrowIfDisposed();
            var eventsJson = JsonSerializer.Serialize(new List<string>(events), JsonOpts);
            var eventsBytes = Utf8Z(eventsJson);
            string resultJson;
            fixed (byte* eventsPtr = eventsBytes)
                resultJson = ConsumeResult(NativeMethods.chat_xdk_extract_conversation_keys(_handle, eventsPtr));
            GC.KeepAlive(this);

            using var doc = JsonDocument.Parse(resultJson);
            return ParseConversationKeyBundle(doc.RootElement);
        }

        /// <summary>
        /// Decrypt a webhook event and return it as a <see cref="JsonElement"/>.
        /// </summary>
        /// <param name="eventB64">Base64-encoded raw event from the webhook.</param>
        /// <param name="conversationKeys">
        /// Map of version → raw 32-byte key bytes from <see cref="ExtractConversationKeys"/> or
        /// <see cref="DecryptEventsResult.ConversationKeys"/>. Pass <see langword="null"/> (or an empty dict)
        /// for non-message events, or to fall back to the opt-in key cache
        /// (<see cref="SetCacheKeys"/>).
        /// </param>
        /// <param name="signingKeys">
        /// Signing keys for the sender. The SDK picks the matching version automatically.
        /// <see langword="null"/> (or an empty list) falls back to the keys stored via
        /// <see cref="SetSigningKeys"/>; if none are stored either, every signed event
        /// throws under the default reject-unverified policy (only after
        /// <see cref="SetRejectUnverified"/>(false) are such events returned with
        /// <c>verified: false</c>).
        /// </param>
        /// <returns>
        /// A <see cref="JsonElement"/> with a <c>"type"</c> field indicating the event kind
        /// (<c>"Message"</c>, <c>"KeyChange"</c>, <c>"GroupChange"</c>, etc.).
        /// </returns>
        public JsonElement DecryptEvent(
            string eventB64,
            Dictionary<string, byte[]>? conversationKeys = null,
            IEnumerable<SigningKeyEntry>? signingKeys = null)
        {
            ThrowIfDisposed();

            // Serialise conv keys as { "version": "base64", ... }
            var convKeysB64 = new Dictionary<string, string>();
            if (conversationKeys != null)
                foreach (var (version, key) in conversationKeys)
                    convKeysB64[version] = Convert.ToBase64String(key);
            var convKeysJson = JsonSerializer.Serialize(convKeysB64, JsonOpts);

            var signingKeysList = signingKeys != null
                ? new List<SigningKeyEntry>(signingKeys)
                : new List<SigningKeyEntry>();
            var signingKeysJson = JsonSerializer.Serialize(signingKeysList, JsonOpts);

            var eventBytes = Utf8Z(eventB64);
            var convBytes = Utf8Z(convKeysJson);
            var sigBytes = Utf8Z(signingKeysJson);
            string resultJson;
            fixed (byte* evtPtr = eventBytes)
            fixed (byte* convPtr = convBytes)
            fixed (byte* sigPtr = sigBytes)
                resultJson = ConsumeResult(
                    NativeMethods.chat_xdk_decrypt_event(_handle, evtPtr, convPtr, sigPtr));
            GC.KeepAlive(this);

            using var doc = JsonDocument.Parse(resultJson);
            return doc.RootElement.Clone();
        }

        /// <summary>
        /// Decrypt a single event using keys from <see cref="ExtractConversationKeys"/> or
        /// <see cref="DecryptEventsResult.ConversationKeys"/> (uses <see cref="ConversationKeyBundle.Keys"/>).
        /// </summary>
        public JsonElement DecryptEvent(
            string eventB64,
            ConversationKeyBundle? conversationKeys,
            IEnumerable<SigningKeyEntry>? signingKeys = null)
            => DecryptEvent(eventB64, conversationKeys?.Keys, signingKeys);

        /// <summary>
        /// Decrypt a batch of webhook events in one call.
        /// Keys are extracted from <c>KeyChange</c> events in the batch; failures are recorded
        /// in <see cref="DecryptEventsResult.Errors"/> — this method never throws per-event.
        /// Passing <see langword="null"/> (or an empty list) for <paramref name="signingKeys"/>
        /// falls back to the keys stored via <see cref="SetSigningKeys"/>.
        /// </summary>
        public DecryptEventsResult DecryptEvents(
            IEnumerable<string> events,
            IEnumerable<SigningKeyEntry>? signingKeys = null)
        {
            ThrowIfDisposed();
            var eventsJson = JsonSerializer.Serialize(new List<string>(events), JsonOpts);
            var signingKeysList = signingKeys != null
                ? new List<SigningKeyEntry>(signingKeys)
                : new List<SigningKeyEntry>();
            var signingKeysJson = JsonSerializer.Serialize(signingKeysList, JsonOpts);
            var eventsBytes = Utf8Z(eventsJson);
            var sigBytes = Utf8Z(signingKeysJson);
            string resultJson;
            fixed (byte* evPtr = eventsBytes)
            fixed (byte* sigPtr = sigBytes)
                resultJson = ConsumeResult(
                    NativeMethods.chat_xdk_decrypt_events(_handle, evPtr, sigPtr));
            GC.KeepAlive(this);

            using var doc = JsonDocument.Parse(resultJson);
            var root = doc.RootElement;

            var messages = new List<DecryptedMessage>();
            foreach (var el in root.GetProperty("messages").EnumerateArray())
            {
                var eventEl = el.GetProperty("event");
                string? orig = null;
                if (el.TryGetProperty("original_b64", out var ob) && ob.ValueKind == JsonValueKind.String)
                    orig = ob.GetString();
                messages.Add(new DecryptedMessage
                {
                    Event = eventEl.Clone(),
                    OriginalB64 = orig,
                });
            }

            var bundle = ParseConversationKeyBundle(root.GetProperty("conversation_keys"));

            var errors = new Dictionary<string, string>();
            foreach (var prop in root.GetProperty("errors").EnumerateObject())
                errors[prop.Name] = prop.Value.GetString() ?? "";

            return new DecryptEventsResult
            {
                Messages = messages,
                ConversationKeys = bundle,
                Errors = errors,
            };
        }

        /// <summary>
        /// Prepare a signed conversation-key change, ready to send to the X API.
        /// Use this to start a one-to-one or rotate an existing conversation's key
        /// (one-to-one or group). Creating a group or adding members requires a paired
        /// group signature as well — use <see cref="PrepareGroupCreate"/> or
        /// <see cref="PrepareGroupMembersChange"/> for those.
        /// Leave <see cref="ConversationKeyChangeParams.ConversationId"/> null for a
        /// one-to-one to derive the canonical id from the two participants; pass the
        /// existing id for a group rotation.
        /// </summary>
        public PreparedConversationChange PrepareConversationKeyChange(ConversationKeyChangeParams parameters)
        {
            ThrowIfDisposed();
            return CallPrepareEndpoint(
                BuildPrepareConversationKeyChangeJson(parameters),
                NativeMethods.chat_xdk_prepare_conversation_key_change);
        }

        /// <summary>
        /// Prepare a signed group member-add change for the updated roster, ready to
        /// send to the X API.
        /// Use this when adding members to an existing group. Creating the group is
        /// <see cref="PrepareGroupCreate"/>; a key rotation without a roster change is
        /// <see cref="PrepareConversationKeyChange"/>.
        /// Emits two action signatures: a conversation-key change and the member add.
        /// </summary>
        public PreparedConversationChange PrepareGroupMembersChange(GroupMembersChangeParams parameters)
        {
            ThrowIfDisposed();
            return CallPrepareEndpoint(
                BuildPrepareGroupMembersChangeJson(parameters),
                NativeMethods.chat_xdk_prepare_group_members_change);
        }

        /// <summary>
        /// Prepare a signed group create for the new roster, ready to send to the X API.
        /// Use this once, when creating a group (the conversation id is the g-prefixed
        /// id minted by the initialize endpoint). Later key rotations use
        /// <see cref="PrepareConversationKeyChange"/>; roster additions use
        /// <see cref="PrepareGroupMembersChange"/>.
        /// Emits two action signatures: a conversation-key change and the group create.
        /// </summary>
        public PreparedConversationChange PrepareGroupCreate(GroupCreateParams parameters)
        {
            ThrowIfDisposed();
            return CallPrepareEndpoint(
                BuildPrepareGroupCreateJson(parameters),
                NativeMethods.chat_xdk_prepare_group_create);
        }

        /// <summary>
        /// Build the signed action for deleting messages from a conversation,
        /// ready to submit alongside the delete request.
        /// A delete is a signed plaintext event, not an encrypted message, so no
        /// conversation key is involved. The SDK generates the action's message
        /// id; read it back from the result.
        /// </summary>
        public ActionSignature PrepareMessageDelete(MessageDeleteParams parameters)
        {
            ThrowIfDisposed();
            var jsonBytes = Utf8Z(BuildPrepareMessageDeleteJson(parameters));
            string resultJson;
            fixed (byte* jsonPtr = jsonBytes)
                resultJson = ConsumeResult(NativeMethods.chat_xdk_prepare_message_delete(_handle, jsonPtr));
            GC.KeepAlive(this);
            return JsonSerializer.Deserialize<ActionSignature>(resultJson, JsonOpts)!;
        }

        // Shared helper: marshal the single-JSON params document, call the
        // native prepare export, deserialise PreparedConversationChange.
        private PreparedConversationChange CallPrepareEndpoint(string paramsJson, ParamsJsonDelegate fn)
        {
            var jsonBytes = Utf8Z(paramsJson);
            string resultJson;
            fixed (byte* jsonPtr = jsonBytes)
                resultJson = ConsumeResult(fn(_handle, jsonPtr));
            GC.KeepAlive(this);
            return JsonSerializer.Deserialize<PreparedConversationChange>(resultJson, JsonOpts)!;
        }

        /// <summary>
        /// Encrypt a UTF-8 metadata string with the conversation key; returns base64 ciphertext (XSalsa20-Poly1305).
        /// </summary>
        public string Encrypt(string plaintext, byte[] conversationKey)
        {
            ThrowIfDisposed();
            ArgumentNullException.ThrowIfNull(conversationKey);
            var pt = Utf8Z(plaintext);
            var ck = Utf8Z(Convert.ToBase64String(conversationKey));
            string ciphertext;
            fixed (byte* ptPtr = pt)
            fixed (byte* ckPtr = ck)
                ciphertext = ConsumeResult(NativeMethods.chat_xdk_encrypt(_handle, ptPtr, ckPtr));
            GC.KeepAlive(this);
            return ciphertext;
        }

        /// <summary>
        /// Decrypt base64 ciphertext (from <see cref="Encrypt"/>) to a UTF-8 plaintext string.
        /// </summary>
        public string Decrypt(string ciphertextB64, byte[] conversationKey)
        {
            ThrowIfDisposed();
            ArgumentNullException.ThrowIfNull(conversationKey);
            var ct = Utf8Z(ciphertextB64);
            var ck = Utf8Z(Convert.ToBase64String(conversationKey));
            string plaintext;
            fixed (byte* ctPtr = ct)
            fixed (byte* ckPtr = ck)
                plaintext = ConsumeResult(NativeMethods.chat_xdk_decrypt(_handle, ctPtr, ckPtr));
            GC.KeepAlive(this);
            return plaintext;
        }

        // Message / reaction / reply encryption

        /// <summary>
        /// Encrypt a message for the X API.
        /// POST the returned <see cref="SendPayload"/> fields to
        /// <c>POST /2/chat/conversations/{id}/messages</c>.
        /// </summary>
        public SendPayload EncryptMessage(EncryptMessageParams parameters)
        {
            ThrowIfDisposed();
            var json = BuildEncryptMessageJson(parameters);
            return CallEncryptEndpoint(json, NativeMethods.chat_xdk_encrypt_message);
        }

        /// <summary>
        /// Encrypt a reply message for the X API.
        /// Like <see cref="EncryptMessage"/> but includes a reply-to preview.
        /// </summary>
        public SendPayload EncryptReply(EncryptReplyParams parameters)
        {
            ThrowIfDisposed();
            var json = BuildEncryptReplyJson(parameters);
            return CallEncryptEndpoint(json, NativeMethods.chat_xdk_encrypt_reply);
        }

        /// <summary>Encrypt a reaction-add for the X API.</summary>
        public SendPayload EncryptAddReaction(EncryptReactionParams parameters)
        {
            ThrowIfDisposed();
            var json = BuildReactionJson(parameters);
            return CallEncryptEndpoint(json, NativeMethods.chat_xdk_encrypt_add_reaction);
        }

        /// <summary>Encrypt a reaction-remove for the X API.</summary>
        public SendPayload EncryptRemoveReaction(EncryptReactionParams parameters)
        {
            ThrowIfDisposed();
            var json = BuildReactionJson(parameters);
            return CallEncryptEndpoint(json, NativeMethods.chat_xdk_encrypt_remove_reaction);
        }

        /// <summary>Encrypt a message edit for the X API.</summary>
        public SendPayload EncryptEdit(EncryptEditParams parameters)
        {
            ThrowIfDisposed();
            var json = BuildEncryptEditJson(parameters);
            return CallEncryptEndpoint(json, NativeMethods.chat_xdk_encrypt_edit);
        }

        // Shared helper: marshal JSON, call the delegate, deserialise SendPayload.
        // FfiResult and ChatHandle are csbindgen-generated types at the ChatXdk namespace level.
        private delegate FfiResult ParamsJsonDelegate(ChatHandle* handle, byte* paramsJson);

        private SendPayload CallEncryptEndpoint(string paramsJson, ParamsJsonDelegate fn)
        {
            var jsonBytes = Utf8Z(paramsJson);
            string resultJson;
            fixed (byte* jsonPtr = jsonBytes)
                resultJson = ConsumeResult(fn(_handle, jsonPtr));
            GC.KeepAlive(this);
            return JsonSerializer.Deserialize<SendPayload>(resultJson, JsonOpts)!;
        }

        // Conversation key operations

        /// <summary>
        /// Decrypt an ECIES-encrypted conversation key from a <c>KeyChange</c> event.
        /// Call this once per key version and cache the result; pass it to
        /// <see cref="DecryptEvent"/> for all subsequent messages.
        /// </summary>
        /// <param name="encryptedKeyB64">
        /// Base64-encoded encrypted key from the <c>KeyChange</c> event
        /// (<c>participant_keys[].encrypted_key</c>).
        /// </param>
        /// <returns>Raw 32-byte decrypted conversation key.</returns>
        public byte[] DecryptConversationKey(string encryptedKeyB64)
        {
            ThrowIfDisposed();
            var encBytes = Utf8Z(encryptedKeyB64);
            string b64;
            fixed (byte* encPtr = encBytes)
                b64 = ConsumeResult(NativeMethods.chat_xdk_decrypt_conversation_key(_handle, encPtr));
            GC.KeepAlive(this);
            return Convert.FromBase64String(b64);
        }

        /// <summary>
        /// Decrypt a streaming-encrypted media payload (e.g. an image or video).
        /// </summary>
        /// <param name="encrypted">Encrypted bytes.</param>
        /// <param name="conversationKey">Raw 32-byte conversation key.</param>
        /// <returns>Decrypted bytes.</returns>
        public byte[] DecryptStream(byte[] encrypted, byte[] conversationKey)
        {
            ThrowIfDisposed();
            var encB64 = Utf8Z(Convert.ToBase64String(encrypted));
            var keyB64 = Utf8Z(Convert.ToBase64String(conversationKey));
            string resultB64;
            fixed (byte* encPtr = encB64)
            fixed (byte* keyPtr = keyB64)
                resultB64 = ConsumeResult(NativeMethods.chat_xdk_decrypt_stream(_handle, encPtr, keyPtr));
            GC.KeepAlive(this);
            return Convert.FromBase64String(resultB64);
        }

        /// <summary>
        /// Encrypt a media payload (e.g. an image or video) with a conversation key.
        /// </summary>
        /// <param name="plaintext">Raw bytes to encrypt.</param>
        /// <param name="conversationKey">Raw 32-byte conversation key.</param>
        /// <returns>Encrypted bytes.</returns>
        public byte[] EncryptStream(byte[] plaintext, byte[] conversationKey)
        {
            ThrowIfDisposed();
            var ptB64 = Utf8Z(Convert.ToBase64String(plaintext));
            var keyB64 = Utf8Z(Convert.ToBase64String(conversationKey));
            string resultB64;
            fixed (byte* ptPtr = ptB64)
            fixed (byte* keyPtr = keyB64)
                resultB64 = ConsumeResult(NativeMethods.chat_xdk_encrypt_stream(_handle, ptPtr, keyPtr));
            GC.KeepAlive(this);
            return Convert.FromBase64String(resultB64);
        }

        /// <summary>
        /// Create an incremental stream encryptor for large payloads.
        /// </summary>
        /// <param name="conversationKey">Raw 32-byte conversation key.</param>
        public StreamEncryptor StreamEncryptor(byte[] conversationKey)
        {
            ThrowIfDisposed();
            return ChatXdk.StreamEncryptor.Create(conversationKey);
        }

        /// <summary>
        /// Create an incremental stream decryptor for large payloads.
        /// </summary>
        /// <param name="conversationKey">Raw 32-byte conversation key.</param>
        public StreamDecryptor StreamDecryptor(byte[] conversationKey)
        {
            ThrowIfDisposed();
            return ChatXdk.StreamDecryptor.Create(conversationKey);
        }

        // Signing / verification

        /// <summary>
        /// Sign arbitrary data with the signing key.
        /// </summary>
        /// <param name="data">Bytes to sign. May be empty but not null.</param>
        /// <returns>64-byte ECDSA P-256 signature.</returns>
        public byte[] Sign(byte[] data)
        {
            ThrowIfDisposed();
            if (data == null) throw new ArgumentNullException(nameof(data));

            string sigB64;
            // For zero-length arrays, fixed can yield a null pointer on some CLR
            // implementations. Pass null explicitly — the Rust side guards data_len == 0.
            if (data.Length == 0)
            {
                sigB64 = ConsumeResult(NativeMethods.chat_xdk_sign(_handle, null, 0));
            }
            else
            {
                fixed (byte* dataPtr = data)
                    sigB64 = ConsumeResult(NativeMethods.chat_xdk_sign(_handle, dataPtr, (nuint)data.Length));
            }
            GC.KeepAlive(this);
            return Convert.FromBase64String(sigB64);
        }

        /// <summary>Verify an ECDSA signature.</summary>
        /// <param name="publicKeyB64">Base64-encoded signing public key (SEC1 or SPKI).</param>
        /// <param name="signature">Raw signature bytes from <see cref="Sign"/>.</param>
        /// <param name="data">The original signed data.</param>
        /// <returns><see langword="true"/> if the signature is valid, <see langword="false"/> if invalid.</returns>
        /// <exception cref="ChatXdkException">
        /// Thrown when the SDK returns an error (e.g. keys not loaded, malformed public key).
        /// An SDK error is always thrown, never returned as a <see langword="false"/> result.
        /// </exception>
        public bool Verify(string publicKeyB64, byte[] signature, byte[] data)
        {
            ThrowIfDisposed();
            if (signature == null) throw new ArgumentNullException(nameof(signature));
            if (data == null) throw new ArgumentNullException(nameof(data));

            var sigB64 = Convert.ToBase64String(signature);
            var pkBytes = Utf8Z(publicKeyB64);
            var sigBytes = Utf8Z(sigB64);
            int rc;

            // data may be empty; handle the zero-length case explicitly so the
            // fixed statement always has a valid (non-null) pinned pointer.
            if (data.Length == 0)
            {
                fixed (byte* pkPtr = pkBytes)
                fixed (byte* sigPtr = sigBytes)
                    rc = NativeMethods.chat_xdk_verify(_handle, pkPtr, sigPtr, null, 0);
            }
            else
            {
                fixed (byte* pkPtr = pkBytes)
                fixed (byte* sigPtr = sigBytes)
                fixed (byte* dataPtr = data)
                    rc = NativeMethods.chat_xdk_verify(_handle, pkPtr, sigPtr, dataPtr, (nuint)data.Length);
            }
            GC.KeepAlive(this);

            return rc switch
            {
                1 => true,
                0 => false,
                // -1: SDK locked, invalid public key format, or bad signature base64.
                // We throw on a -1 error code.
                _ => throw new ChatXdkException(
                    "Signature verification error — ensure the SDK is unlocked and the public key is valid."),
            };
        }

        /// <summary>
        /// Verify that a signing key is authentically bound to an identity key.
        /// Call this when you receive another user's public keys from the X API
        /// to detect server-side key substitution. All arguments are base64.
        /// </summary>
        public bool VerifyKeyBinding(string identityPublicKeyB64, string signingPublicKeyB64, string identityPublicKeySignatureB64)
        {
            ThrowIfDisposed();
            var identityBytes = Utf8Z(identityPublicKeyB64);
            var signingBytes = Utf8Z(signingPublicKeyB64);
            var sigBytes = Utf8Z(identityPublicKeySignatureB64);
            int rc;
            fixed (byte* identityPtr = identityBytes)
            fixed (byte* signingPtr = signingBytes)
            fixed (byte* sigPtr = sigBytes)
                rc = NativeMethods.chat_xdk_verify_key_binding(_handle, identityPtr, signingPtr, sigPtr);
            GC.KeepAlive(this);

            return rc switch
            {
                1 => true,
                0 => false,
                _ => throw new ChatXdkException(
                    "Key binding verification error — ensure the inputs are valid base64."),
            };
        }

        /// <summary>
        /// Report whether the loaded identity public key is the key in
        /// <paramref name="publicKeyB64"/>. The X API returns the identity
        /// public key in SPKI/DER encoding while GetPublicKeys returns the
        /// raw SEC1 point; this accepts either encoding, so use it to check
        /// whether the keys on this device belong to a key registered to
        /// the account.
        /// </summary>
        public bool MatchesRegisteredKey(string publicKeyB64)
        {
            ThrowIfDisposed();
            var pkBytes = Utf8Z(publicKeyB64);
            int rc;
            fixed (byte* pkPtr = pkBytes)
                rc = NativeMethods.chat_xdk_matches_registered_key(_handle, pkPtr);
            GC.KeepAlive(this);

            return rc switch
            {
                1 => true,
                0 => false,
                _ => throw new ChatXdkException(
                    "Registered key match error — ensure keys are loaded and the input is valid base64."),
            };
        }

        // JSON builders for the single-JSON params documents

        // A null in any optional slot serializes as JSON null (WhenWritingNull
        // does not apply to dictionary entries), which the FFI reads as unset —
        // the value then resolves from the session identity / key cache.
        private static string BuildEncryptMessageJson(EncryptMessageParams p)
        {
            var dict = new Dictionary<string, object?>
            {
                ["conversation_id"] = p.ConversationId,
                ["text"] = p.Text,
                ["sender_id"] = p.SenderId,
                ["signing_key_version"] = p.SigningKeyVersion,
                ["conversation_key"] = p.ConversationKey != null ? Convert.ToBase64String(p.ConversationKey) : null,
                ["conversation_key_version"] = p.ConversationKeyVersion,
                ["entities"] = p.Entities != null ? SerialiseEntities(p.Entities) : null,
                ["attachments"] = p.Attachments,
                ["should_notify"] = p.ShouldNotify,
                ["ttl_msec"] = p.TtlMsec,
            };
            return JsonSerializer.Serialize(dict, JsonOpts);
        }

        private static string BuildEncryptReplyJson(EncryptReplyParams p)
        {
            var dict = new Dictionary<string, object?>
            {
                ["conversation_id"] = p.ConversationId,
                ["text"] = p.Text,
                ["reply_to_event"] = p.ReplyToEvent,
                ["reply_to_edit_event"] = p.ReplyToEditEvent,
                ["reply_to_ckces"] = p.ReplyToCkces,
                ["sender_id"] = p.SenderId,
                ["signing_key_version"] = p.SigningKeyVersion,
                ["conversation_key"] = p.ConversationKey != null ? Convert.ToBase64String(p.ConversationKey) : null,
                ["conversation_key_version"] = p.ConversationKeyVersion,
                ["reply_to_sequence_id"] = p.ReplyToSequenceId,
                ["reply_to_sender_id"] = p.ReplyToSenderId,
                ["reply_to_text"] = p.ReplyToText,
                ["entities"] = p.Entities != null ? SerialiseEntities(p.Entities) : null,
                ["attachments"] = p.Attachments,
                ["reply_to_entities"] = p.ReplyToEntities != null ? SerialiseEntities(p.ReplyToEntities) : null,
                ["reply_to_attachments"] = p.ReplyToAttachments,
                ["should_notify"] = p.ShouldNotify,
                ["ttl_msec"] = p.TtlMsec,
            };
            return JsonSerializer.Serialize(dict, JsonOpts);
        }

        private static string BuildReactionJson(EncryptReactionParams p)
        {
            var dict = new Dictionary<string, object?>
            {
                ["target_event"] = p.TargetEvent,
                ["emoji"] = p.Emoji,
                ["conversation_id"] = p.ConversationId,
                ["target_message_sequence_id"] = p.TargetMessageSequenceId,
                ["sender_id"] = p.SenderId,
                ["signing_key_version"] = p.SigningKeyVersion,
                ["conversation_key"] = p.ConversationKey != null ? Convert.ToBase64String(p.ConversationKey) : null,
                ["conversation_key_version"] = p.ConversationKeyVersion,
            };
            return JsonSerializer.Serialize(dict, JsonOpts);
        }

        private static string BuildEncryptEditJson(EncryptEditParams p)
        {
            var dict = new Dictionary<string, object?>
            {
                ["target_event"] = p.TargetEvent,
                ["updated_text"] = p.UpdatedText,
                ["entities"] = p.Entities != null ? SerialiseEntities(p.Entities) : null,
                ["conversation_id"] = p.ConversationId,
                ["target_message_sequence_id"] = p.TargetMessageSequenceId,
                ["sender_id"] = p.SenderId,
                ["signing_key_version"] = p.SigningKeyVersion,
                ["conversation_key"] = p.ConversationKey != null ? Convert.ToBase64String(p.ConversationKey) : null,
                ["conversation_key_version"] = p.ConversationKeyVersion,
            };
            return JsonSerializer.Serialize(dict, JsonOpts);
        }

        private static string BuildPrepareMessageDeleteJson(MessageDeleteParams p)
        {
            var dict = new Dictionary<string, object?>
            {
                ["conversation_id"] = p.ConversationId,
                ["sequence_ids"] = p.SequenceIds,
                ["delete_for_all"] = p.DeleteForAll,
                ["sender_id"] = p.SenderId,
                ["signing_key_version"] = p.SigningKeyVersion,
            };
            return JsonSerializer.Serialize(dict, JsonOpts);
        }

        private static string BuildPrepareConversationKeyChangeJson(ConversationKeyChangeParams p)
        {
            var dict = new Dictionary<string, object?>
            {
                ["public_keys"] = p.PublicKeys,
                ["sender_id"] = p.SenderId,
                ["signing_key_version"] = p.SigningKeyVersion,
                ["conversation_id"] = p.ConversationId,
            };
            return JsonSerializer.Serialize(dict, JsonOpts);
        }

        private static string BuildPrepareGroupMembersChangeJson(GroupMembersChangeParams p)
        {
            var dict = new Dictionary<string, object?>
            {
                ["public_keys"] = p.PublicKeys,
                ["conversation_id"] = p.ConversationId,
                ["sender_id"] = p.SenderId,
                ["signing_key_version"] = p.SigningKeyVersion,
                ["new_member_ids"] = p.NewMemberIds,
                ["current_member_ids"] = p.CurrentMemberIds,
                ["current_admin_ids"] = p.CurrentAdminIds,
                ["current_pending_member_ids"] = p.CurrentPendingMemberIds,
                ["current_title"] = p.CurrentTitle,
                ["current_avatar_url"] = p.CurrentAvatarUrl,
                ["current_ttl_msec"] = p.CurrentTtlMsec,
                // An unset value serializes as JSON null (WhenWritingNull does
                // not apply to dictionary entries), which the FFI reads as
                // unset — never a false default.
                ["current_screen_capture_blocking_enabled"] = p.CurrentScreenCaptureBlockingEnabled,
            };
            return JsonSerializer.Serialize(dict, JsonOpts);
        }

        private static string BuildPrepareGroupCreateJson(GroupCreateParams p)
        {
            var dict = new Dictionary<string, object?>
            {
                ["public_keys"] = p.PublicKeys,
                ["conversation_id"] = p.ConversationId,
                ["sender_id"] = p.SenderId,
                ["signing_key_version"] = p.SigningKeyVersion,
                ["member_ids"] = p.MemberIds,
                ["admin_ids"] = p.AdminIds,
                ["title"] = p.Title,
                ["avatar_url"] = p.AvatarUrl,
                ["ttl_msec"] = p.TtlMsec,
            };
            return JsonSerializer.Serialize(dict, JsonOpts);
        }

        // Entities are serialised as [[start, end, "type"], ...] tuples.
        private static object[][] SerialiseEntities(IReadOnlyList<EntityDescriptor> entities)
        {
            var result = new object[entities.Count][];
            for (int i = 0; i < entities.Count; i++)
            {
                var e = entities[i];
                result[i] = new object[] { e.Start, e.End, e.EntityType };
            }
            return result;
        }
    }

    /// <summary>
    /// Thrown when the native chat-xdk library returns an error.
    /// </summary>
    public sealed class ChatXdkException : Exception
    {
        // Stable invalid-PIN message form the core emits
        // ("Invalid PIN: guesses_remaining=N"). Anchored on the full form so a
        // count embedded in an unrelated pass-through message is not misread.
        private static readonly System.Text.RegularExpressions.Regex GuessesRemainingPattern =
            new(@"\bInvalid PIN: guesses_remaining=(\d+)", System.Text.RegularExpressions.RegexOptions.Compiled);

        public ChatXdkException(string message) : base(message)
        {
            var match = GuessesRemainingPattern.Match(message ?? "");
            if (match.Success && int.TryParse(match.Groups[1].Value, out var n))
            {
                GuessesRemaining = n;
            }
        }

        /// <summary>
        /// Remaining PIN attempts reported by Juicebox, or <see langword="null"/> when the
        /// message carries no count.
        ///
        /// <para>Present only on invalid-PIN <see cref="Chat.Unlock"/> /
        /// <see cref="Chat.ChangePin"/> failures. <c>0</c> means the guess budget is
        /// exhausted and the stored keys are locked.</para>
        /// </summary>
        public int? GuessesRemaining { get; }
    }
}
