// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace ChatXdk
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "chat_xdk_dotnet";





        /// <summary>
        ///  Create a new Chat SDK instance.
        ///
        ///  Returns an opaque handle that must be freed with `chat_xdk_free`.
        ///  Returns NULL on allocation failure.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ChatHandle* chat_xdk_new();

        /// <summary>
        ///  Free a Chat SDK handle.
        ///
        ///  After this call the handle is invalid. Passing NULL is a no-op.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void chat_xdk_free(ChatHandle* handle);

        /// <summary>
        ///  Free a string returned by any `chat_xdk_*` function.
        ///
        ///  The buffer is zeroized before it is freed: some returns carry secrets
        ///  (e.g. exported keys), so every returned string is wiped rather than
        ///  deciding per call site.
        ///
        ///  Passing NULL is a no-op.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void chat_xdk_free_string(byte* s);

        /// <summary>
        ///  Returns 1 if both identity and signing keys are loaded, 0 if locked, -1 on null handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_is_unlocked", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int chat_xdk_is_unlocked(ChatHandle* handle);

        /// <summary>
        ///  Returns 1 if the identity key is loaded (sufficient for decryption), 0 if not, -1 on null handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_has_identity_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int chat_xdk_has_identity_key(ChatHandle* handle);

        /// <summary>
        ///  When `reject` is non-zero — the default — `chat_xdk_decrypt_event` returns
        ///  an error for any signed event whose signature cannot be verified (invalid,
        ///  missing, or no matching signing key) instead of returning it with
        ///  `verified: false`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_set_reject_unverified", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void chat_xdk_set_reject_unverified(ChatHandle* handle, int reject);

        /// <summary>
        ///  Set the session identity: the owner's user id and signing-key version,
        ///  used as the defaults wherever a params document omits `sender_id` /
        ///  `signing_key_version`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_set_identity", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_set_identity(ChatHandle* handle, byte* user_id, byte* signing_key_version);

        /// <summary>
        ///  Enable (non-zero) or disable (zero) the conversation-key cache (off by
        ///  default). While enabled, `chat_xdk_decrypt_events` caches, per
        ///  conversation, the key whose key change carried a valid signature at the
        ///  highest version seen, and the encrypt entry points resolve an omitted
        ///  `conversation_key`/`conversation_key_version` pair from it. Disabling
        ///  clears the cache.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_set_cache_keys", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void chat_xdk_set_cache_keys(ChatHandle* handle, int enabled);

        /// <summary>
        ///  Store signing keys to use when a decrypt call passes an empty
        ///  `signing_keys_json`. Only this explicit call populates the store — a key
        ///  carried inside an event is never trusted for verification. Each call
        ///  replaces the previous set.
        ///
        ///  `signing_keys_json`: same array shape as `chat_xdk_decrypt_events`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_set_signing_keys", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_set_signing_keys(ChatHandle* handle, byte* signing_keys_json);

        /// <summary>
        ///  Lock the SDK, clearing all key material from memory.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_lock", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void chat_xdk_lock(ChatHandle* handle);

        /// <summary>
        ///  Update the Juicebox configuration (e.g. to refresh short-lived auth tokens).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_update_config", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_update_config(ChatHandle* handle, byte* config_json);

        /// <summary>
        ///  Register the SDK's keys with Juicebox (first-time setup).
        ///
        ///  `config_json` is the Juicebox configuration from the X API.
        ///  Returns JSON `{"identity":"...","signing":"...","version":"..."}` on success.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_setup", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_setup(ChatHandle* handle, byte* pin, byte* config_json);

        /// <summary>
        ///  Recover keys from Juicebox and unlock the SDK.
        ///
        ///  `config_json` is the Juicebox configuration from the X API.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_unlock", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_unlock(ChatHandle* handle, byte* pin, byte* config_json);

        /// <summary>
        ///  Delete keys from Juicebox and lock the SDK.
        ///
        ///  Warning: Irreversible — the user will lose access to their encrypted history.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_delete", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_delete(ChatHandle* handle);

        /// <summary>
        ///  Re-register keys under a new PIN.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_change_pin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_change_pin(ChatHandle* handle, byte* old_pin, byte* new_pin);

        /// <summary>
        ///  Generate new identity + signing keypairs.
        ///
        ///  Returns JSON matching `PublicKeyRegistrationPayload` for the X API.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_generate_keypairs", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_generate_keypairs(ChatHandle* handle);

        /// <summary>
        ///  Get the user's current public keys.
        ///
        ///  Returns JSON `{"identity":"...","signing":"...","version":"..."}`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_get_public_keys", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_get_public_keys(ChatHandle* handle);

        /// <summary>
        ///  Get the fingerprint of the loaded identity public key.
        ///
        ///  Returns a URL-safe base64 string (SHA-256 of the SPKI-encoded key) for
        ///  out-of-band verification.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_get_public_key_fingerprint", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_get_public_key_fingerprint(ChatHandle* handle);

        /// <summary>
        ///  Export private key material as a base64 string for secure backup.
        ///
        ///  Returns empty data (NULL `data` field) if no identity key is loaded.
        ///  Warning: Handle the result with extreme care — this is raw secret key material.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_export_keys", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_export_keys(ChatHandle* handle);

        /// <summary>
        ///  Import private key material from a base64 string produced by `chat_xdk_export_keys`.
        ///
        ///  Accepts 32 bytes (identity only) or 64 bytes (identity + signing).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_import_keys", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_import_keys(ChatHandle* handle, byte* keys_b64);

        /// <summary>
        ///  Like `chat_xdk_import_keys` but takes the raw key bytes and also records
        ///  the public key version the keys were registered under, so participant-key
        ///  filtering and the session `signing_key_version` are set in one call.
        ///
        ///  Accepts 32 bytes (identity only) or 64 bytes (identity + signing).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_import_keys_with_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_import_keys_with_version(ChatHandle* handle, byte* keys, nuint keys_len, byte* version);

        /// <summary>
        ///  Extract and decrypt conversation keys from raw KeyChange event strings.
        ///
        ///  `events_json` — JSON array of base64-encoded raw event strings from the webhook.
        ///
        ///  Returns JSON `{"keys":{"version":"base64_bytes",...},"latest_version":"..."|null}`.
        ///  Pass `keys` serialized as a flat map `{"version":"base64_bytes",...}` to `chat_xdk_decrypt_event`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_extract_conversation_keys", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_extract_conversation_keys(ChatHandle* handle, byte* events_json);

        /// <summary>
        ///  Batch decrypt. `signing_keys_json`: `[{"user_id","public_key_version","public_key",
        ///  "identity_public_key","identity_public_key_signature"},...]`. An empty
        ///  array falls back to the keys stored via `chat_xdk_set_signing_keys`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_decrypt_events", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_decrypt_events(ChatHandle* handle, byte* events_json, byte* signing_keys_json);

        /// <summary>
        ///  Prepare a signed conversation-key change.
        ///
        ///  `params_json` — single JSON document: `public_keys`
        ///  (`[{"user_id","public_key","key_version"},...]`), plus optional
        ///  `sender_id` / `signing_key_version` (absent resolves from the session
        ///  identity set via `chat_xdk_set_identity`) and optional `conversation_id`
        ///  (absent or empty derives the one-to-one id).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_prepare_conversation_key_change", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_prepare_conversation_key_change(ChatHandle* handle, byte* params_json);

        /// <summary>
        ///  Prepare a signed group member-add change.
        ///
        ///  `params_json` — single JSON document: `public_keys` (for the updated
        ///  roster), `conversation_id`, `new_member_ids`, `current_member_ids`,
        ///  `current_admin_ids`, `current_pending_member_ids`, plus optional
        ///  `sender_id` / `signing_key_version` (absent resolves from the session
        ///  identity), `current_title`, `current_avatar_url`, `current_ttl_msec`, and
        ///  `current_screen_capture_blocking_enabled` (an absent key means unset,
        ///  never false). Emits two action signatures.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_prepare_group_members_change", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_prepare_group_members_change(ChatHandle* handle, byte* params_json);

        /// <summary>
        ///  Prepare a signed group create.
        ///
        ///  `params_json` — single JSON document: `public_keys` (for the roster),
        ///  `conversation_id`, `member_ids`, `admin_ids`, plus optional `sender_id` /
        ///  `signing_key_version` (absent resolves from the session identity),
        ///  `title`, `avatar_url`, and `ttl_msec`. Emits two action signatures.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_prepare_group_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_prepare_group_create(ChatHandle* handle, byte* params_json);

        /// <summary>
        ///  Decrypt a webhook event.
        ///
        ///  - `event_b64` — base64-encoded raw event from the webhook.
        ///  - `conversation_keys_json` — JSON object `{"version": "base64_key"}` from
        ///    `chat_xdk_extract_conversation_keys`. Pass `"{}"` for non-message events
        ///    or to fall back to the opt-in key cache (`chat_xdk_set_cache_keys`).
        ///  - `signing_keys_json` — JSON array `[{"user_id","public_key_version","public_key",
        ///    "identity_public_key","identity_public_key_signature"},...]` for the sender.
        ///    The SDK selects the matching version automatically. An empty array falls
        ///    back to the keys stored via `chat_xdk_set_signing_keys`; if none are
        ///    stored either, signed events fail decryption under the default
        ///    reject-unverified policy (disable it via `chat_xdk_set_reject_unverified`
        ///    to have them returned with `verified: false` instead).
        ///
        ///  Returns a JSON representation of the decrypted `Event`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_decrypt_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_decrypt_event(ChatHandle* handle, byte* event_b64, byte* conversation_keys_json, byte* signing_keys_json);

        /// <summary>
        ///  Encrypt a message for the X API.
        ///
        ///  `params_json` — single JSON document: `conversation_id` and `text`, plus
        ///  optional overrides `sender_id` / `signing_key_version` (absent resolves
        ///  from the session identity) and `conversation_key` (base64 raw 32-byte
        ///  key) / `conversation_key_version` (absent resolves from the opt-in key
        ///  cache), plus optional `entities` (`[[start,end,"type"],...]`),
        ///  `attachments` (`[{"attachment_type",...},...]`), `should_notify`, and
        ///  `ttl_msec`.
        ///
        ///  Returns JSON `SendPayload`; the SDK-generated `message_id` is a field on it.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_encrypt_message", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_encrypt_message(ChatHandle* handle, byte* params_json);

        /// <summary>
        ///  Encrypt a reply message for the X API.
        ///
        ///  `params_json` — same document as `chat_xdk_encrypt_message` plus
        ///  `reply_to_event` (base64 raw signed event being replied to; the reply
        ///  preview is derived from it) with optional `reply_to_edit_event` and
        ///  `reply_to_ckces` (base64 raw key-change events needed to decrypt the
        ///  original under an older key version). The explicit-preview overrides
        ///  `reply_to_sequence_id`, `reply_to_sender_id`, `reply_to_text`,
        ///  `reply_to_entities`, and `reply_to_attachments` remain for callers that no
        ///  longer hold the raw event.
        ///
        ///  Returns JSON `SendPayload`; the SDK-generated `message_id` is a field on it.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_encrypt_reply", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_encrypt_reply(ChatHandle* handle, byte* params_json);

        /// <summary>
        ///  Encrypt a reaction-add for the X API.
        ///
        ///  `params_json` — single JSON document: `emoji` and `target_event` (base64
        ///  raw event being reacted to; the conversation id and target sequence id are
        ///  derived from it), plus optional explicit overrides `conversation_id` /
        ///  `target_message_sequence_id` for callers that no longer hold the raw
        ///  event, and the optional identity/key overrides described on
        ///  `chat_xdk_encrypt_message`.
        ///
        ///  Returns JSON `SendPayload`; the SDK-generated `message_id` is a field on it.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_encrypt_add_reaction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_encrypt_add_reaction(ChatHandle* handle, byte* params_json);

        /// <summary>
        ///  Encrypt a reaction-remove for the X API.
        ///
        ///  Same parameters as `chat_xdk_encrypt_add_reaction`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_encrypt_remove_reaction", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_encrypt_remove_reaction(ChatHandle* handle, byte* params_json);

        /// <summary>
        ///  Decrypt an ECIES-encrypted conversation key.
        ///
        ///  `encrypted_key_b64` — base64-encoded encrypted key from a `KeyChange` event.
        ///
        ///  Returns a base64-encoded raw 32-byte conversation key.
        ///  Call this once per key version; reuse the result for all subsequent operations.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_decrypt_conversation_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_decrypt_conversation_key(ChatHandle* handle, byte* encrypted_key_b64);

        /// <summary>
        ///  Encrypt a UTF-8 plaintext string; returns base64 ciphertext (XSalsa20-Poly1305).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_encrypt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_encrypt(ChatHandle* handle, byte* plaintext, byte* conversation_key_b64);

        /// <summary>
        ///  Decrypt base64 ciphertext to UTF-8 plaintext (metadata fields).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_decrypt", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_decrypt(ChatHandle* handle, byte* ciphertext_b64, byte* conversation_key_b64);

        /// <summary>
        ///  Decrypt a streaming-encrypted payload (e.g. media files).
        ///
        ///  Both arguments are base64-encoded.
        ///  Returns base64-encoded decrypted bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_decrypt_stream", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_decrypt_stream(ChatHandle* handle, byte* encrypted_b64, byte* conversation_key_b64);

        /// <summary>
        ///  Encrypt a stream (e.g. media files) with a conversation key.
        ///
        ///  Both arguments are base64-encoded.
        ///  Returns base64-encoded encrypted bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_encrypt_stream", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_encrypt_stream(ChatHandle* handle, byte* plaintext_b64, byte* conversation_key_b64);

        /// <summary>
        ///  Create a stream encryptor for a base64 conversation key. Returns NULL on a
        ///  bad key; free the handle with `chat_xdk_stream_encryptor_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_stream_encryptor_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern StreamEncryptorHandle* chat_xdk_stream_encryptor_new(byte* conversation_key_b64);

        /// <summary>
        ///  Encrypt a base64 plaintext chunk; returns base64 ciphertext available so far.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_stream_encryptor_push", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_stream_encryptor_push(StreamEncryptorHandle* handle, byte* plaintext_b64);

        /// <summary>
        ///  Emit the final frame as base64. The handle must still be freed afterwards.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_stream_encryptor_finish", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_stream_encryptor_finish(StreamEncryptorHandle* handle);

        /// <summary>
        ///  Free a stream encryptor handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_stream_encryptor_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void chat_xdk_stream_encryptor_free(StreamEncryptorHandle* handle);

        /// <summary>
        ///  Create a stream decryptor for a base64 conversation key. Returns NULL on a
        ///  bad key; free the handle with `chat_xdk_stream_decryptor_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_stream_decryptor_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern StreamDecryptorHandle* chat_xdk_stream_decryptor_new(byte* conversation_key_b64);

        /// <summary>
        ///  Decrypt a base64 ciphertext chunk; returns base64 plaintext available so far.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_stream_decryptor_push", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_stream_decryptor_push(StreamDecryptorHandle* handle, byte* ciphertext_b64);

        /// <summary>
        ///  Decrypt the final frame as base64. Errors if the stream was truncated. The
        ///  handle must still be freed afterwards.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_stream_decryptor_finish", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_stream_decryptor_finish(StreamDecryptorHandle* handle);

        /// <summary>
        ///  Free a stream decryptor handle.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_stream_decryptor_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void chat_xdk_stream_decryptor_free(StreamDecryptorHandle* handle);

        /// <summary>
        ///  Sign arbitrary data with the signing key.
        ///
        ///  Returns a base64-encoded ECDSA signature (64 bytes).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_sign", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_sign(ChatHandle* handle, byte* data, nuint data_len);

        /// <summary>
        ///  Verify an ECDSA signature.
        ///
        ///  `public_key_b64` — base64-encoded signing public key (SEC1 or SPKI).
        ///  `signature_b64` — base64-encoded signature from `chat_xdk_sign`.
        ///  `data` / `data_len` — the original signed data.
        ///
        ///  Returns 1 if valid, 0 if invalid, -1 on error.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_verify", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int chat_xdk_verify(ChatHandle* handle, byte* public_key_b64, byte* signature_b64, byte* data, nuint data_len);

        /// <summary>
        ///  Verify that a signing key is authentically bound to an identity key.
        ///
        ///  All three arguments are base64 strings. Returns 1 if valid, 0 if not,
        ///  and -1 on error.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_verify_key_binding", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int chat_xdk_verify_key_binding(ChatHandle* handle, byte* identity_public_key_b64, byte* signing_public_key_b64, byte* identity_public_key_signature_b64);

        /// <summary>
        ///  Report whether the loaded identity public key is the key in
        ///  `public_key_b64` (raw SEC1 point or SPKI/DER, base64-encoded).
        ///
        ///  Returns 1 on a match, 0 on a mismatch, and -1 on error (no identity
        ///  keypair loaded or malformed input).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_matches_registered_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int chat_xdk_matches_registered_key(ChatHandle* handle, byte* public_key_b64);

        /// <summary>
        ///  Encode bytes to standard base64.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_bytes_to_base64", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_bytes_to_base64(byte* data, nuint data_len);

        /// <summary>
        ///  Decode base64 to bytes. On success, `data` holds base64 of the decoded bytes (FFI-safe).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_base64_to_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_base64_to_bytes(byte* b64);

        /// <summary>
        ///  Encode bytes to lowercase hex.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_bytes_to_hex", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_bytes_to_hex(byte* data, nuint data_len);

        /// <summary>
        ///  Decode hex to bytes. On success, `data` holds base64 of the decoded bytes (FFI-safe).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_hex_to_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_hex_to_bytes(byte* hex);

        /// <summary>
        ///  Detect MIME type from magic bytes. Empty string if unknown.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_detect_mime_type", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_detect_mime_type(byte* data, nuint data_len);

        /// <summary>
        ///  JSON `{"width":N,"height":M}` or the literal `null` if dimensions cannot be determined.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "chat_xdk_detect_image_dimensions", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiResult chat_xdk_detect_image_dimensions(byte* data, nuint data_len);


    }

    /// <summary>
    ///  Result returned by every fallible FFI function.
    ///
    ///  Exactly one of `data` / `error` is non-NULL on return.
    ///  The non-NULL field **must** be freed with `chat_xdk_free_string`.
    ///  If both are NULL the operation succeeded with no output (void).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct FfiResult
    {
        public byte* data;
        public byte* error;
    }

    /// <summary>
    ///  Opaque handle to a live Chat SDK session.
    ///
    ///  Allocated by `chat_xdk_new`, released by `chat_xdk_free`.
    ///  All methods require a non-NULL handle; passing NULL returns an error result
    ///  or -1 / no-op, depending on the function's return type.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ChatHandle
    {
    }

    /// <summary>
    ///  Opaque handle to an incremental stream encryptor.
    ///
    ///  Created by `chat_xdk_stream_encryptor_new`, freed by
    ///  `chat_xdk_stream_encryptor_free`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct StreamEncryptorHandle
    {
    }

    /// <summary>
    ///  Opaque handle to an incremental stream decryptor.
    ///
    ///  Created by `chat_xdk_stream_decryptor_new`, freed by
    ///  `chat_xdk_stream_decryptor_free`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct StreamDecryptorHandle
    {
    }



}
