// Autogenerated by Thrift Compiler (0.24.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

#[derive(Copy, Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct GroupOpType(pub i32);

impl GroupOpType {
  pub const GEN_GROUP: GroupOpType = GroupOpType(1);
  pub const EDIT: GroupOpType = GroupOpType(6);
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::GEN_GROUP,
    Self::EDIT,
  ];
}

impl TSerializable for GroupOpType {
  #[allow(clippy::trivially_copy_pass_by_ref)]
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    o_prot.write_i32(self.0)
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<GroupOpType> {
    let enum_value = i_prot.read_i32()?;
    Ok(GroupOpType::from(enum_value))
  }
}

impl From<i32> for GroupOpType {
  fn from(i: i32) -> Self {
    match i {
      1 => GroupOpType::GEN_GROUP,
      6 => GroupOpType::EDIT,
      _ => GroupOpType(i)
    }
  }
}

impl From<&i32> for GroupOpType {
  fn from(i: &i32) -> Self {
    GroupOpType::from(*i)
  }
}

impl From<GroupOpType> for i32 {
  fn from(e: GroupOpType) -> i32 {
    e.0
  }
}

impl From<&GroupOpType> for i32 {
  fn from(e: &GroupOpType) -> i32 {
    e.0
  }
}

//
// Member
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Member {
  pub user_id: i64,
  pub key_version: i64,
}

impl Member {
  pub fn new(user_id: i64, key_version: i64) -> Member {
    Member {
      user_id,
      key_version,
    }
  }
}

impl TSerializable for Member {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<Member> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = None;
    let mut f_2: Option<i64> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("Member.user_id", &f_1)?;
    verify_required_field_exists("Member.key_version", &f_2)?;
    let ret = Member {
      user_id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      key_version: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("Member");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("userId", TType::I64, 1))?;
    o_prot.write_i64(self.user_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("keyVersion", TType::I64, 2))?;
    o_prot.write_i64(self.key_version)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PubKeyBytes
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PubKeyBytes {
  pub pub_key_bytes: Vec<u8>,
}

impl PubKeyBytes {
  pub fn new(pub_key_bytes: Vec<u8>) -> PubKeyBytes {
    PubKeyBytes {
      pub_key_bytes,
    }
  }
}

impl TSerializable for PubKeyBytes {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PubKeyBytes> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<u8>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_bytes()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("PubKeyBytes.pub_key_bytes", &f_1)?;
    let ret = PubKeyBytes {
      pub_key_bytes: f_1.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("PubKeyBytes");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("pubKeyBytes", TType::String, 1))?;
    o_prot.write_bytes(&self.pub_key_bytes)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// MemberKeyInfo
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MemberKeyInfo {
  pub identity_public_key: Option<Vec<u8>>,
  pub signing_public_key: Option<Vec<u8>>,
  pub identity_key_signature: Option<Vec<u8>>,
}

impl MemberKeyInfo {
  pub fn new<F1, F2, F3>(identity_public_key: F1, signing_public_key: F2, identity_key_signature: F3) -> MemberKeyInfo where F1: Into<Option<Vec<u8>>>, F2: Into<Option<Vec<u8>>>, F3: Into<Option<Vec<u8>>> {
    MemberKeyInfo {
      identity_public_key: identity_public_key.into(),
      signing_public_key: signing_public_key.into(),
      identity_key_signature: identity_key_signature.into(),
    }
  }
}

impl TSerializable for MemberKeyInfo {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<MemberKeyInfo> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Vec<u8>> = None;
    let mut f_2: Option<Vec<u8>> = None;
    let mut f_3: Option<Vec<u8>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_bytes()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bytes()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_bytes()?;
          f_3 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = MemberKeyInfo {
      identity_public_key: f_1,
      signing_public_key: f_2,
      identity_key_signature: f_3,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("MemberKeyInfo");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.identity_public_key {
      o_prot.write_field_begin(&TFieldIdentifier::new("identityPublicKey", TType::String, 1))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.signing_public_key {
      o_prot.write_field_begin(&TFieldIdentifier::new("signingPublicKey", TType::String, 2))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.identity_key_signature {
      o_prot.write_field_begin(&TFieldIdentifier::new("identityKeySignature", TType::String, 3))?;
      o_prot.write_bytes(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TreeKeyData
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TreeKeyData {
  pub public_key: PubKeyBytes,
  pub sub_tree_hash: Vec<u8>,
}

impl TreeKeyData {
  pub fn new(public_key: PubKeyBytes, sub_tree_hash: Vec<u8>) -> TreeKeyData {
    TreeKeyData {
      public_key,
      sub_tree_hash,
    }
  }
}

impl TSerializable for TreeKeyData {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TreeKeyData> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<PubKeyBytes> = None;
    let mut f_2: Option<Vec<u8>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = PubKeyBytes::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_bytes()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("TreeKeyData.public_key", &f_1)?;
    verify_required_field_exists("TreeKeyData.sub_tree_hash", &f_2)?;
    let ret = TreeKeyData {
      public_key: f_1.expect("auto-generated code should have checked for presence of required fields"),
      sub_tree_hash: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TreeKeyData");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("publicKey", TType::Struct, 1))?;
    self.public_key.write_to_out_protocol(o_prot)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("subTreeHash", TType::String, 2))?;
    o_prot.write_bytes(&self.sub_tree_hash)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TreeNode
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TreeNode {
  pub member: Option<Member>,
  pub key_data: Option<TreeKeyData>,
  pub node_secret_key_encryptions: Option<BTreeMap<Vec<u8>, Vec<u8>>>,
}

impl TreeNode {
  pub fn new<F1, F2, F3>(member: F1, key_data: F2, node_secret_key_encryptions: F3) -> TreeNode where F1: Into<Option<Member>>, F2: Into<Option<TreeKeyData>>, F3: Into<Option<BTreeMap<Vec<u8>, Vec<u8>>>> {
    TreeNode {
      member: member.into(),
      key_data: key_data.into(),
      node_secret_key_encryptions: node_secret_key_encryptions.into(),
    }
  }
}

impl TSerializable for TreeNode {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TreeNode> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<Member> = None;
    let mut f_2: Option<TreeKeyData> = None;
    let mut f_3: Option<BTreeMap<Vec<u8>, Vec<u8>>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = Member::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        2 => {
          let val = TreeKeyData::read_from_in_protocol(i_prot)?;
          f_2 = Some(val);
        },
        3 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<Vec<u8>, Vec<u8>> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_0 = i_prot.read_bytes()?;
            let map_val_1 = i_prot.read_bytes()?;
            val.insert(map_key_0, map_val_1);
          }
          i_prot.read_map_end()?;
          f_3 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = TreeNode {
      member: f_1,
      key_data: f_2,
      node_secret_key_encryptions: f_3,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TreeNode");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.member {
      o_prot.write_field_begin(&TFieldIdentifier::new("member", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.key_data {
      o_prot.write_field_begin(&TFieldIdentifier::new("keyData", TType::Struct, 2))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.node_secret_key_encryptions {
      o_prot.write_field_begin(&TFieldIdentifier::new("nodeSecretKeyEncryptions", TType::Map, 3))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::String, TType::String, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_bytes(k)?;
        o_prot.write_bytes(v)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// MaybeTreeNode
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct MaybeTreeNode {
  pub node: Option<TreeNode>,
}

impl MaybeTreeNode {
  pub fn new<F1>(node: F1) -> MaybeTreeNode where F1: Into<Option<TreeNode>> {
    MaybeTreeNode {
      node: node.into(),
    }
  }
}

impl TSerializable for MaybeTreeNode {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<MaybeTreeNode> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<TreeNode> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = TreeNode::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = MaybeTreeNode {
      node: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("MaybeTreeNode");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.node {
      o_prot.write_field_begin(&TFieldIdentifier::new("node", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// GroupOpData
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct GroupOpData {
  pub group_id: Option<String>,
  pub tree_version: Option<i64>,
  pub action_by: Option<Member>,
  pub type_data: Option<Box<TypeData>>,
  pub member_key_info: Option<BTreeMap<i64, MemberKeyInfo>>,
}

impl GroupOpData {
  pub fn new<F1, F2, F3, F4, F6>(group_id: F1, tree_version: F2, action_by: F3, type_data: F4, member_key_info: F6) -> GroupOpData where F1: Into<Option<String>>, F2: Into<Option<i64>>, F3: Into<Option<Member>>, F4: Into<Option<Box<TypeData>>>, F6: Into<Option<BTreeMap<i64, MemberKeyInfo>>> {
    GroupOpData {
      group_id: group_id.into(),
      tree_version: tree_version.into(),
      action_by: action_by.into(),
      type_data: type_data.into(),
      member_key_info: member_key_info.into(),
    }
  }
}

impl TSerializable for GroupOpData {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<GroupOpData> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<String> = None;
    let mut f_2: Option<i64> = None;
    let mut f_3: Option<Member> = None;
    let mut f_4: Option<Box<TypeData>> = None;
    let mut f_6: Option<BTreeMap<i64, MemberKeyInfo>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = Member::read_from_in_protocol(i_prot)?;
          f_3 = Some(val);
        },
        4 => {
          match TypeData::read_from_in_protocol(i_prot) {
            Ok(val) => { f_4 = Some(Box::new(val)); },
            Err(thrift::Error::Protocol(ref e)) if e.kind == ProtocolErrorKind::UnknownUnionVariant => {
            },
            Err(e) => return Err(e),
          }
        },
        6 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<i64, MemberKeyInfo> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_2 = i_prot.read_i64()?;
            let map_val_3 = MemberKeyInfo::read_from_in_protocol(i_prot)?;
            val.insert(map_key_2, map_val_3);
          }
          i_prot.read_map_end()?;
          f_6 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = GroupOpData {
      group_id: f_1,
      tree_version: f_2,
      action_by: f_3,
      type_data: f_4,
      member_key_info: f_6,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("GroupOpData");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.group_id {
      o_prot.write_field_begin(&TFieldIdentifier::new("groupId", TType::String, 1))?;
      o_prot.write_string(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.tree_version {
      o_prot.write_field_begin(&TFieldIdentifier::new("treeVersion", TType::I64, 2))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.action_by {
      o_prot.write_field_begin(&TFieldIdentifier::new("actionBy", TType::Struct, 3))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.type_data {
      o_prot.write_field_begin(&TFieldIdentifier::new("typeData", TType::Struct, 4))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.member_key_info {
      o_prot.write_field_begin(&TFieldIdentifier::new("memberKeyInfo", TType::Map, 6))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::I64, TType::Struct, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_i64(*k)?;
        v.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// TypeData
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum TypeData {
  GenGroup(Box<GenGroupOpData>),
  Edit(Box<EditOpData>),
}

impl TSerializable for TypeData {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<TypeData> {
    let mut ret: Option<TypeData> = None;
    let mut received_field_count = 0;
    let mut total_field_count = 0;
    i_prot.read_struct_begin()?;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = Box::new(GenGroupOpData::read_from_in_protocol(i_prot)?);
          if ret.is_none() {
            ret = Some(TypeData::GenGroup(val));
          }
          received_field_count += 1;
        },
        6 => {
          let val = Box::new(EditOpData::read_from_in_protocol(i_prot)?);
          if ret.is_none() {
            ret = Some(TypeData::Edit(val));
          }
          received_field_count += 1;
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      total_field_count += 1;
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    if total_field_count == 0 {
      Err(
        thrift::Error::Protocol(
          ProtocolError::new(
            ProtocolErrorKind::EmptyUnion,
            "received empty union from remote TypeData"
          )
        )
      )
    } else if received_field_count > 1 {
      Err(
        thrift::Error::Protocol(
          ProtocolError::new(
            ProtocolErrorKind::InvalidData,
            "received multiple fields for union from remote TypeData"
          )
        )
      )
    } else if received_field_count == 0 {
      Err(
        thrift::Error::Protocol(
          ProtocolError::new(
            ProtocolErrorKind::UnknownUnionVariant,
            "received union with unknown variant from remote TypeData"
          )
        )
      )
    } else if let Some(ret) = ret {
      Ok(ret)
    } else {
      Err(
        thrift::Error::Protocol(
          ProtocolError::new(ProtocolErrorKind::InvalidData, "return value should have been constructed")
        )
      )
    }
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("TypeData");
    o_prot.write_struct_begin(&struct_ident)?;
    match *self {
      TypeData::GenGroup(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("genGroup", TType::Struct, 1))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
      TypeData::Edit(ref f) => {
        o_prot.write_field_begin(&TFieldIdentifier::new("edit", TType::Struct, 6))?;
        f.write_to_out_protocol(o_prot)?;
        o_prot.write_field_end()?;
      },
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// GenGroupOpData
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct GenGroupOpData {
  pub update_map: Option<BTreeMap<i32, BTreeMap<Vec<u8>, Vec<u8>>>>,
  pub new_path_pks: Option<BTreeMap<i32, Vec<u8>>>,
  pub initial_members: Option<Vec<Member>>,
}

impl GenGroupOpData {
  pub fn new<F1, F2, F3>(update_map: F1, new_path_pks: F2, initial_members: F3) -> GenGroupOpData where F1: Into<Option<BTreeMap<i32, BTreeMap<Vec<u8>, Vec<u8>>>>>, F2: Into<Option<BTreeMap<i32, Vec<u8>>>>, F3: Into<Option<Vec<Member>>> {
    GenGroupOpData {
      update_map: update_map.into(),
      new_path_pks: new_path_pks.into(),
      initial_members: initial_members.into(),
    }
  }
}

impl TSerializable for GenGroupOpData {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<GenGroupOpData> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<BTreeMap<i32, BTreeMap<Vec<u8>, Vec<u8>>>> = None;
    let mut f_2: Option<BTreeMap<i32, Vec<u8>>> = None;
    let mut f_3: Option<Vec<Member>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<i32, BTreeMap<Vec<u8>, Vec<u8>>> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_4 = i_prot.read_i32()?;
            let map_ident = i_prot.read_map_begin()?;
            let mut map_val_5: BTreeMap<Vec<u8>, Vec<u8>> = BTreeMap::new();
            for _ in 0..map_ident.size {
              let map_key_6 = i_prot.read_bytes()?;
              let map_val_7 = i_prot.read_bytes()?;
              map_val_5.insert(map_key_6, map_val_7);
            }
            i_prot.read_map_end()?;
            val.insert(map_key_4, map_val_5);
          }
          i_prot.read_map_end()?;
          f_1 = Some(val);
        },
        2 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<i32, Vec<u8>> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_8 = i_prot.read_i32()?;
            let map_val_9 = i_prot.read_bytes()?;
            val.insert(map_key_8, map_val_9);
          }
          i_prot.read_map_end()?;
          f_2 = Some(val);
        },
        3 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<Member> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_10 = Member::read_from_in_protocol(i_prot)?;
            val.push(list_elem_10);
          }
          i_prot.read_list_end()?;
          f_3 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = GenGroupOpData {
      update_map: f_1,
      new_path_pks: f_2,
      initial_members: f_3,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("GenGroupOpData");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.update_map {
      o_prot.write_field_begin(&TFieldIdentifier::new("updateMap", TType::Map, 1))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::I32, TType::Map, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_i32(*k)?;
        o_prot.write_map_begin(&TMapIdentifier::new(TType::String, TType::String, v.len() as i32))?;
        for (k, v) in v {
          o_prot.write_bytes(k)?;
          o_prot.write_bytes(v)?;
        }
        o_prot.write_map_end()?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.new_path_pks {
      o_prot.write_field_begin(&TFieldIdentifier::new("newPathPks", TType::Map, 2))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::I32, TType::String, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_i32(*k)?;
        o_prot.write_bytes(v)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.initial_members {
      o_prot.write_field_begin(&TFieldIdentifier::new("initialMembers", TType::List, 3))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// EditOpData
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct EditOpData {
  pub update_map: Option<BTreeMap<i32, BTreeMap<Vec<u8>, Vec<u8>>>>,
  pub new_path_pks: Option<BTreeMap<i32, Vec<u8>>>,
  pub members_left: Option<Vec<Member>>,
  pub members_to_add: Option<Vec<Member>>,
  pub members_updated: Option<Vec<Member>>,
  pub full_tree_list: Option<Vec<MaybeTreeNode>>,
}

impl EditOpData {
  pub fn new<F1, F2, F3, F4, F5, F6>(update_map: F1, new_path_pks: F2, members_left: F3, members_to_add: F4, members_updated: F5, full_tree_list: F6) -> EditOpData where F1: Into<Option<BTreeMap<i32, BTreeMap<Vec<u8>, Vec<u8>>>>>, F2: Into<Option<BTreeMap<i32, Vec<u8>>>>, F3: Into<Option<Vec<Member>>>, F4: Into<Option<Vec<Member>>>, F5: Into<Option<Vec<Member>>>, F6: Into<Option<Vec<MaybeTreeNode>>> {
    EditOpData {
      update_map: update_map.into(),
      new_path_pks: new_path_pks.into(),
      members_left: members_left.into(),
      members_to_add: members_to_add.into(),
      members_updated: members_updated.into(),
      full_tree_list: full_tree_list.into(),
    }
  }
}

impl TSerializable for EditOpData {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<EditOpData> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<BTreeMap<i32, BTreeMap<Vec<u8>, Vec<u8>>>> = None;
    let mut f_2: Option<BTreeMap<i32, Vec<u8>>> = None;
    let mut f_3: Option<Vec<Member>> = None;
    let mut f_4: Option<Vec<Member>> = None;
    let mut f_5: Option<Vec<Member>> = None;
    let mut f_6: Option<Vec<MaybeTreeNode>> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<i32, BTreeMap<Vec<u8>, Vec<u8>>> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_11 = i_prot.read_i32()?;
            let map_ident = i_prot.read_map_begin()?;
            let mut map_val_12: BTreeMap<Vec<u8>, Vec<u8>> = BTreeMap::new();
            for _ in 0..map_ident.size {
              let map_key_13 = i_prot.read_bytes()?;
              let map_val_14 = i_prot.read_bytes()?;
              map_val_12.insert(map_key_13, map_val_14);
            }
            i_prot.read_map_end()?;
            val.insert(map_key_11, map_val_12);
          }
          i_prot.read_map_end()?;
          f_1 = Some(val);
        },
        2 => {
          let map_ident = i_prot.read_map_begin()?;
          let mut val: BTreeMap<i32, Vec<u8>> = BTreeMap::new();
          for _ in 0..map_ident.size {
            let map_key_15 = i_prot.read_i32()?;
            let map_val_16 = i_prot.read_bytes()?;
            val.insert(map_key_15, map_val_16);
          }
          i_prot.read_map_end()?;
          f_2 = Some(val);
        },
        3 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<Member> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_17 = Member::read_from_in_protocol(i_prot)?;
            val.push(list_elem_17);
          }
          i_prot.read_list_end()?;
          f_3 = Some(val);
        },
        4 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<Member> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_18 = Member::read_from_in_protocol(i_prot)?;
            val.push(list_elem_18);
          }
          i_prot.read_list_end()?;
          f_4 = Some(val);
        },
        5 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<Member> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_19 = Member::read_from_in_protocol(i_prot)?;
            val.push(list_elem_19);
          }
          i_prot.read_list_end()?;
          f_5 = Some(val);
        },
        6 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<MaybeTreeNode> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_20 = MaybeTreeNode::read_from_in_protocol(i_prot)?;
            val.push(list_elem_20);
          }
          i_prot.read_list_end()?;
          f_6 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = EditOpData {
      update_map: f_1,
      new_path_pks: f_2,
      members_left: f_3,
      members_to_add: f_4,
      members_updated: f_5,
      full_tree_list: f_6,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("EditOpData");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.update_map {
      o_prot.write_field_begin(&TFieldIdentifier::new("updateMap", TType::Map, 1))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::I32, TType::Map, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_i32(*k)?;
        o_prot.write_map_begin(&TMapIdentifier::new(TType::String, TType::String, v.len() as i32))?;
        for (k, v) in v {
          o_prot.write_bytes(k)?;
          o_prot.write_bytes(v)?;
        }
        o_prot.write_map_end()?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.new_path_pks {
      o_prot.write_field_begin(&TFieldIdentifier::new("newPathPks", TType::Map, 2))?;
      o_prot.write_map_begin(&TMapIdentifier::new(TType::I32, TType::String, fld_var.len() as i32))?;
      for (k, v) in fld_var {
        o_prot.write_i32(*k)?;
        o_prot.write_bytes(v)?;
      }
      o_prot.write_map_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.members_left {
      o_prot.write_field_begin(&TFieldIdentifier::new("membersLeft", TType::List, 3))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.members_to_add {
      o_prot.write_field_begin(&TFieldIdentifier::new("membersToAdd", TType::List, 4))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.members_updated {
      o_prot.write_field_begin(&TFieldIdentifier::new("membersUpdated", TType::List, 5))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.full_tree_list {
      o_prot.write_field_begin(&TFieldIdentifier::new("fullTreeList", TType::List, 6))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::Struct, fld_var.len() as i32))?;
      for e in fld_var {
        e.write_to_out_protocol(o_prot)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

