//! Python bindings for chat-xdk encryption library.
//!
//! Provides a simple, Pythonic interface to the X Chat SDK.
//!
//! # Quick Start
//!
//! ```python
//! from chat_xdk import Chat
//!
//! chat = Chat()
//! chat.unlock(pin)
//! chat.set_identity(my_user_id, signing_key_version)
//!
//! # Decrypt an event (returns a dict). `conversation_keys` maps key version
//! # to the raw 32-byte key (from extract_conversation_keys); `signing_keys`
//! # is the list of signing-key dicts for the sender.
//! event = chat.decrypt_event(event_b64, conversation_keys, signing_keys)
//! print(event["type"])  # "Message", "KeyChange", etc.
//!
//! # Encrypt a message with the raw 32-byte conversation key
//! payload = chat.encrypt_message(conversation_id, "Hello!",
//!                                conversation_key=conversation_key,
//!                                conversation_key_version=conversation_key_version)
//! # payload.message_id (generated by the SDK), payload.encrypted_content, etc.
//! ```

use pyo3::prelude::*;
use pyo3::types::{PyByteArray, PyBytes};
use pyo3::Py;
use std::collections::HashMap;
use std::io::Cursor;
use std::sync::Arc;

use chat_xdk_core::keys::juicebox::{JuiceboxClient, JuiceboxConfig};
use chat_xdk_core::{
    AttachmentDescriptor, ConversationKeyChangeParams, EncryptMessageParams, EncryptReactionParams,
    EncryptReplyParams, EntityDescriptor, GroupCreateParams, GroupMembersChangeParams,
};

/// Parse the X API Juicebox config JSON into a [`JuiceboxConfig`].
fn parse_juicebox_config(config_json: &str) -> PyResult<JuiceboxConfig> {
    JuiceboxConfig::from_x_api_json(config_json)
        .map_err(PyErr::new::<pyo3::exceptions::PyValueError, _>)
}

/// Extract a PIN from `str`, `bytes`, or `bytearray` into a buffer that is
/// wiped on drop. `bytearray` additionally lets the caller zero their own
/// copy afterwards — `str`/`bytes` are immutable and stay in interpreter
/// memory until garbage-collected. Exact downcasts keep the accepted types
/// to those three; other sequences of ints (e.g. `list[int]`) are rejected.
fn extract_pin(pin: &Bound<'_, PyAny>) -> PyResult<zeroize::Zeroizing<Vec<u8>>> {
    if let Ok(s) = pin.extract::<&str>() {
        return Ok(zeroize::Zeroizing::new(s.as_bytes().to_vec()));
    }
    if let Ok(b) = pin.cast::<PyBytes>() {
        return Ok(zeroize::Zeroizing::new(b.as_bytes().to_vec()));
    }
    if let Ok(b) = pin.cast::<PyByteArray>() {
        return Ok(zeroize::Zeroizing::new(b.to_vec()));
    }
    Err(PyErr::new::<pyo3::exceptions::PyTypeError, _>(
        "pin must be str, bytes, or bytearray",
    ))
}

/// Convert Python entity tuples `(start, end, type)` into [`EntityDescriptor`]s.
fn parse_entity_descs(tuples: Vec<(i32, i32, String)>) -> Vec<EntityDescriptor> {
    tuples
        .into_iter()
        .map(|(start, end, entity_type)| EntityDescriptor {
            start,
            end,
            entity_type,
        })
        .collect()
}

/// Convert Python attachment dicts into [`AttachmentDescriptor`]s.
///
/// Each dict must have an `"attachment_type"` key (`"media"`, `"url"`, or
/// `"post"`) plus the relevant fields for that type. `"url"` attachments
/// accept optional `"banner_image"`/`"favicon_image"` dicts (each with
/// required `"media_hash_key"`, `"filesize_bytes"`, and `"filename"`)
/// referencing encrypted preview images.
fn parse_attachment_descs(
    dicts: Vec<HashMap<String, Py<PyAny>>>,
) -> PyResult<Vec<AttachmentDescriptor>> {
    Python::attach(|py| {
        let json_mod = py.import("json")?;
        let json_str: String = json_mod
            .call_method1("dumps", (dicts,))?
            .extract()
            .map_err(|_| {
                PyErr::new::<pyo3::exceptions::PyValueError, _>(
                    "Attachments are not JSON-serializable",
                )
            })?;
        // Deserialize via the core serde types so the field requirements are
        // defined once in core: an attachment missing a required media field
        // is rejected rather than silently defaulted.
        serde_json::from_str(&json_str).map_err(|e| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(format!("Invalid attachments: {}", e))
        })
    })
}

/// Convert a signing-key dict into a core `SigningKeyEntry`, surfacing a
/// `ValueError` if a required field is missing instead of silently dropping
/// the entry (which would weaken signature verification).
fn parse_signing_key_entry(
    mut m: std::collections::HashMap<String, String>,
) -> PyResult<chat_xdk_core::SigningKeyEntry> {
    let require = |m: &mut std::collections::HashMap<String, String>, field: &str| {
        m.remove(field).ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(format!(
                "signing key missing required field '{}'",
                field
            ))
        })
    };
    Ok(chat_xdk_core::SigningKeyEntry {
        user_id: require(&mut m, "user_id")?,
        public_key_version: require(&mut m, "public_key_version")?,
        public_key: require(&mut m, "public_key")?,
        identity_public_key: require(&mut m, "identity_public_key")?,
        identity_public_key_signature: require(&mut m, "identity_public_key_signature")?,
    })
}

/// Assemble reaction params shared by ``encrypt_add_reaction`` and
/// ``encrypt_remove_reaction``. ``emoji`` sits after the optional
/// ``target_event`` positional, so it carries a ``None`` sentinel instead of
/// being required in the pyo3 signature; a missing emoji raises ``TypeError``
/// like any other missing required argument.
#[allow(clippy::too_many_arguments)]
fn build_reaction_params(
    target_event: Option<String>,
    emoji: Option<String>,
    conversation_id: Option<String>,
    target_message_sequence_id: Option<String>,
    sender_id: Option<String>,
    signing_key_version: Option<String>,
    conversation_key: Option<Vec<u8>>,
    conversation_key_version: Option<String>,
) -> PyResult<EncryptReactionParams> {
    let emoji = emoji.ok_or_else(|| {
        PyErr::new::<pyo3::exceptions::PyTypeError, _>("missing required argument: 'emoji'")
    })?;
    let mut params = EncryptReactionParams::new(target_event.unwrap_or_default(), emoji);
    params.conversation_id = conversation_id;
    params.target_message_sequence_id = target_message_sequence_id;
    params.sender_id = sender_id;
    params.signing_key_version = signing_key_version;
    params.conversation_key = conversation_key;
    params.conversation_key_version = conversation_key_version;
    Ok(params)
}

fn to_py_err(e: impl std::error::Error) -> PyErr {
    let mut msg = e.to_string();
    let mut source = e.source();
    while let Some(err) = source {
        msg.push_str("\ncaused by: ");
        msg.push_str(&err.to_string());
        source = err.source();
    }
    PyErr::new::<pyo3::exceptions::PyValueError, _>(msg)
}

/// Parse a list of ``{user_id, public_key, key_version}`` dicts into core inputs.
fn parse_public_key_inputs(
    public_keys: Vec<std::collections::HashMap<String, String>>,
) -> PyResult<Vec<chat_xdk_core::PublicKeyInput>> {
    public_keys
        .into_iter()
        .map(|mut r| {
            Ok(chat_xdk_core::PublicKeyInput {
                user_id: r.remove("user_id").ok_or_else(|| {
                    PyErr::new::<pyo3::exceptions::PyValueError, _>("missing 'user_id'")
                })?,
                public_key: r.remove("public_key").ok_or_else(|| {
                    PyErr::new::<pyo3::exceptions::PyValueError, _>("missing 'public_key'")
                })?,
                key_version: r.remove("key_version").ok_or_else(|| {
                    PyErr::new::<pyo3::exceptions::PyValueError, _>("missing 'key_version'")
                })?,
            })
        })
        .collect()
}

/// Build the Python dict for a prepared key change.
fn prepared_change_to_pydict(
    py: Python<'_>,
    result: &chat_xdk_core::PreparedConversationChange,
) -> PyResult<Py<PyAny>> {
    let outer = pyo3::types::PyDict::new(py);
    outer.set_item("conversation_id", &result.conversation_id)?;
    if let Some(ckey) = &result.conversation_key {
        outer.set_item(
            "conversation_key",
            ckey.encoded().to_vec().into_pyobject(py)?,
        )?;
    }
    outer.set_item("conversation_key_version", &result.conversation_key_version)?;

    let participant_keys = pyo3::types::PyList::empty(py);
    for item in &result.participant_keys {
        let dict = pyo3::types::PyDict::new(py);
        dict.set_item("user_id", &item.user_id)?;
        dict.set_item("encrypted_key", &item.encrypted_key)?;
        dict.set_item("public_key_version", &item.public_key_version)?;
        participant_keys.append(dict)?;
    }
    outer.set_item("participant_keys", participant_keys)?;

    let action_signatures = pyo3::types::PyList::empty(py);
    for sig in &result.action_signatures {
        let dict = pyo3::types::PyDict::new(py);
        dict.set_item("message_id", &sig.message_id)?;
        dict.set_item(
            "encoded_message_event_detail",
            &sig.encoded_message_event_detail,
        )?;
        dict.set_item("signature", &sig.signature)?;
        dict.set_item("signature_version", &sig.signature_version)?;
        dict.set_item("public_key_version", &sig.public_key_version)?;
        // Absent for conversation-key changes: the signed payload embeds the
        // plaintext conversation key and is withheld.
        if !sig.signature_payload.is_empty() {
            dict.set_item("signature_payload", &sig.signature_payload)?;
        }
        action_signatures.append(dict)?;
    }
    outer.set_item("action_signatures", action_signatures)?;

    Ok(outer.into())
}

/// Convert the core SendPayload to the Python SendPayload with matching shape.
fn to_py_send_payload(payload: chat_xdk_core::SendPayload) -> SendPayload {
    SendPayload {
        message_id: payload.message_id,
        encrypted_content: payload.encrypted_content,
        signature: payload.signature,
        encoded_event_signature: payload.encoded_event_signature,
        signature_info: SignatureInfo {
            public_key_version: payload.signature_info.public_key_version,
            signature_version: payload.signature_info.signature_version,
        },
        conversation_key_version: payload.conversation_key_version,
        should_notify: payload.should_notify,
    }
}

/// Public keys returned by setup/get_public_keys.
#[pyclass]
#[derive(Clone)]
pub struct PublicKeys {
    /// Base64-encoded identity public key (P-256, for ECDH).
    #[pyo3(get)]
    pub identity: String,
    /// Base64-encoded signing public key (P-256, for ECDSA).
    #[pyo3(get)]
    pub signing: String,
    /// Key version identifier.
    #[pyo3(get)]
    pub version: String,
}

/// Public key registration payload returned by generate_keypairs().
#[pyclass]
#[derive(Clone)]
pub struct PublicKeyRegistrationPayload {
    #[pyo3(get)]
    pub public_key: PublicKeyRegistration,
    #[pyo3(get)]
    pub version: Option<String>,
    #[pyo3(get)]
    pub generate_version: bool,
}

/// Public key registration fields expected by the X API.
#[pyclass]
#[derive(Clone)]
pub struct PublicKeyRegistration {
    #[pyo3(get)]
    pub identity_public_key_signature: String,
    #[pyo3(get)]
    pub public_key: String,
    #[pyo3(get)]
    pub public_key_fingerprint: Option<String>,
    #[pyo3(get)]
    pub registration_method: String,
    #[pyo3(get)]
    pub signing_public_key: String,
    #[pyo3(get)]
    pub signing_public_key_signature: Option<String>,
}

/// Signature metadata for a sent message.
#[pyclass]
#[derive(Clone)]
pub struct SignatureInfo {
    /// Version of the signing key used.
    #[pyo3(get)]
    pub public_key_version: String,
    /// Signature protocol version (e.g. "7").
    #[pyo3(get)]
    pub signature_version: String,
}

/// Encrypted message payload ready to send to the X API.
#[pyclass]
#[derive(Clone)]
pub struct SendPayload {
    /// SDK-generated message id (UUID) embedded in the signed event. Send it as
    /// the message's ``message_id``, keep it to dedup and to anchor replies, and
    /// reuse the same encrypted payload on retries so an id is never minted twice.
    #[pyo3(get)]
    pub message_id: String,
    /// Base64-encoded encrypted message content.
    #[pyo3(get)]
    pub encrypted_content: String,
    /// Base64-encoded signature.
    #[pyo3(get)]
    pub signature: String,
    /// Base64-encoded Thrift `MessageEventSignature` (for `encoded_message_event_signature`).
    #[pyo3(get)]
    pub encoded_event_signature: String,
    /// Signature metadata (public_key_version + signature_version).
    #[pyo3(get)]
    pub signature_info: SignatureInfo,
    /// Conversation key version used.
    #[pyo3(get)]
    pub conversation_key_version: String,
    /// Whether to send push notification.
    #[pyo3(get)]
    pub should_notify: bool,
}

/// The main Chat SDK interface.
///
/// Example:
/// ```python
/// chat = Chat(config_json)  # or Chat() then update_config(...)
/// chat.unlock(pin)
/// chat.set_identity(my_user_id, signing_key_version)
///
/// # Decrypt webhook events
/// event = chat.decrypt_event(event_b64, conversation_keys, signing_keys)
/// if event["type"] == "Message":
///     print(event["content"]["text"])
///
/// # Encrypt outgoing messages
/// payload = chat.encrypt_message(conversation_id, "Hello!",
///                                conversation_key=key, conversation_key_version=version)
/// ```
#[pyclass]
pub struct Chat {
    inner: chat_xdk_core::Chat,
    runtime: tokio::runtime::Runtime,
}

#[pymethods]
impl Chat {
    /// Create a new Chat instance.
    ///
    /// Args:
    ///     config_json: Juicebox configuration JSON.
    ///         Pass ``None`` or an empty JSON object (e.g. ``"{}"``) for
    ///         manual key management without Juicebox.
    #[new]
    #[pyo3(signature = (config_json=None))]
    fn new(config_json: Option<&str>) -> PyResult<Self> {
        let runtime = tokio::runtime::Runtime::new()
            .map_err(|e| PyErr::new::<pyo3::exceptions::PyRuntimeError, _>(e.to_string()))?;

        let config = match config_json {
            // An empty JSON object means manual key management, same as None.
            // Anything else (including unparseable JSON) goes through the X
            // API config parser, which reports the malformed field.
            Some(json) => match serde_json::from_str::<serde_json::Value>(json) {
                Ok(serde_json::Value::Object(m)) if m.is_empty() => {
                    JuiceboxConfig::from_json("{}".to_string())
                }
                _ => parse_juicebox_config(json)?,
            },
            None => JuiceboxConfig::from_json("{}".to_string()),
        };
        let inner = chat_xdk_core::Chat::with_juicebox(config, Arc::new(JuiceboxClient::new()));

        Ok(Self { inner, runtime })
    }

    /// Update the Juicebox configuration (e.g. to refresh auth tokens).
    fn update_config(&mut self, config_json: &str) -> PyResult<()> {
        let config = parse_juicebox_config(config_json)?;
        self.inner.update_config(config);
        Ok(())
    }

    /// Returns True when both identity and signing keys are loaded.
    fn is_unlocked(&self) -> bool {
        self.inner.is_unlocked()
    }

    /// Returns True when the identity key is loaded (sufficient for decryption).
    fn has_identity_key(&self) -> bool {
        self.inner.has_identity_key()
    }

    /// When enabled — the default — `decrypt_event` raises for any signed
    /// event whose signature cannot be verified (invalid, missing, or no
    /// matching signing key) instead of returning it with `verified: false`.
    fn set_reject_unverified(&mut self, reject: bool) {
        self.inner.set_reject_unverified(reject);
    }

    /// Set the session identity: your user id and registered signing-key
    /// version, used as the defaults wherever a method's ``sender_id`` /
    /// ``signing_key_version`` argument is omitted. A resolved default and an
    /// explicitly passed value produce identical signed output.
    fn set_identity(&self, user_id: &str, signing_key_version: &str) {
        self.inner.set_identity(user_id, signing_key_version);
    }

    /// Enable or disable the conversation-key cache (off by default).
    ///
    /// While enabled, ``decrypt_events`` caches each conversation's latest
    /// signature-verified key, and the encrypt methods resolve an omitted
    /// ``conversation_key``/``conversation_key_version`` pair from it.
    /// Disabling clears the cache.
    fn set_cache_keys(&self, enabled: bool) {
        self.inner.set_cache_keys(enabled);
    }

    /// Store signing keys to use when a decrypt call omits its
    /// ``signing_keys`` argument.
    ///
    /// Args:
    ///     signing_keys: Same list of dicts ``decrypt_events`` takes. Each
    ///         call replaces the previous set; only this call populates the
    ///         store — keys carried inside events are never trusted.
    fn set_signing_keys(
        &self,
        signing_keys: Vec<std::collections::HashMap<String, String>>,
    ) -> PyResult<()> {
        let entries = signing_keys
            .into_iter()
            .map(parse_signing_key_entry)
            .collect::<PyResult<Vec<_>>>()?;
        self.inner.set_signing_keys(entries);
        Ok(())
    }

    /// Lock the SDK, clearing keys from memory.
    fn lock(&self) {
        self.inner.lock()
    }

    /// Delete keys from Juicebox and clear from memory.
    ///
    /// Warning: This is irreversible. The user will lose access to their encrypted messages.
    fn delete(&mut self, py: Python<'_>) -> PyResult<()> {
        // Release the GIL for the Juicebox round trips so other Python
        // threads keep running; no Python objects cross into the closure.
        let inner = &mut self.inner;
        let runtime = &self.runtime;
        py.detach(|| runtime.block_on(async { inner.delete().await.map_err(to_py_err) }))
    }

    /// Register existing keys with Juicebox.
    ///
    /// Args:
    ///     pin: The user's PIN for key protection (str, bytes, or bytearray;
    ///         a bytearray can be zeroed by the caller afterwards).
    ///
    /// Returns:
    ///     PublicKeys with identity and signing keys.
    fn setup(&mut self, py: Python<'_>, pin: &Bound<'_, PyAny>) -> PyResult<PublicKeys> {
        let pin = extract_pin(pin)?;
        // Release the GIL for the Juicebox round trips so other Python
        // threads keep running; no Python objects cross into the closure.
        let inner = &mut self.inner;
        let runtime = &self.runtime;
        let keys =
            py.detach(|| runtime.block_on(async { inner.setup(&pin).await.map_err(to_py_err) }))?;

        Ok(PublicKeys {
            identity: keys.identity,
            signing: keys.signing,
            version: keys.version,
        })
    }

    /// Unlock the SDK by recovering keys from Juicebox.
    ///
    /// Args:
    ///     pin: The user's PIN (str, bytes, or bytearray; a bytearray can be
    ///         zeroed by the caller afterwards).
    fn unlock(&mut self, py: Python<'_>, pin: &Bound<'_, PyAny>) -> PyResult<()> {
        let pin = extract_pin(pin)?;
        // Release the GIL for the Juicebox round trips so other Python
        // threads keep running; no Python objects cross into the closure.
        let inner = &mut self.inner;
        let runtime = &self.runtime;
        py.detach(|| runtime.block_on(async { inner.unlock(&pin).await.map_err(to_py_err) }))
    }

    /// Re-register keys with a new PIN.
    ///
    /// Args:
    ///     old_pin: The current PIN (str, bytes, or bytearray).
    ///     new_pin: The new PIN to set (str, bytes, or bytearray).
    fn change_pin(
        &mut self,
        py: Python<'_>,
        old_pin: &Bound<'_, PyAny>,
        new_pin: &Bound<'_, PyAny>,
    ) -> PyResult<()> {
        let old_pin = extract_pin(old_pin)?;
        let new_pin = extract_pin(new_pin)?;
        // Release the GIL for the Juicebox round trips so other Python
        // threads keep running; no Python objects cross into the closure.
        let inner = &mut self.inner;
        let runtime = &self.runtime;
        py.detach(|| {
            runtime.block_on(async {
                inner
                    .change_pin(&old_pin, &new_pin)
                    .await
                    .map_err(to_py_err)
            })
        })
    }

    /// Generate new keypairs and return the registration payload.
    ///
    /// Returns:
    ///     PublicKeyRegistrationPayload for the X API.
    fn generate_keypairs(&self) -> PyResult<PublicKeyRegistrationPayload> {
        let payload = self.inner.generate_keypairs().map_err(to_py_err)?;
        Ok(PublicKeyRegistrationPayload {
            public_key: PublicKeyRegistration {
                identity_public_key_signature: payload.public_key.identity_public_key_signature,
                public_key: payload.public_key.public_key,
                public_key_fingerprint: payload.public_key.public_key_fingerprint,
                registration_method: payload.public_key.registration_method,
                signing_public_key: payload.public_key.signing_public_key,
                signing_public_key_signature: payload.public_key.signing_public_key_signature,
            },
            version: payload.version,
            generate_version: payload.generate_version,
        })
    }

    /// Get the user's public keys.
    fn get_public_keys(&self) -> PyResult<PublicKeys> {
        let keys = self.inner.get_public_keys().map_err(to_py_err)?;
        Ok(PublicKeys {
            identity: keys.identity,
            signing: keys.signing,
            version: keys.version,
        })
    }

    /// Get the fingerprint of the loaded identity public key.
    ///
    /// Returns a URL-safe base64 string (SHA-256 of the SPKI-encoded key)
    /// that users can compare out-of-band to verify key authenticity.
    fn get_public_key_fingerprint(&self) -> PyResult<String> {
        self.inner.get_public_key_fingerprint().map_err(to_py_err)
    }

    /// Extract and decrypt conversation keys from raw KeyChange event strings.
    ///
    /// Args:
    ///     events: List of base64-encoded raw event strings (from webhook).
    ///
    /// Returns:
    ///     A dict with:
    ///     - ``keys``: Dict mapping key version string to raw 32-byte conversation key (``bytes``)
    ///     - ``latest_version``: The highest key version (use for encrypting new messages)
    fn extract_conversation_keys(&self, events: Vec<String>) -> PyResult<Py<PyAny>> {
        let refs: Vec<&str> = events.iter().map(|s| s.as_str()).collect();
        let result = self.inner.extract_conversation_keys(&refs);

        Python::attach(|py| {
            let outer = pyo3::types::PyDict::new(py);

            // Build keys dict
            let keys_dict = pyo3::types::PyDict::new(py);
            for (version, key) in result.keys {
                keys_dict.set_item(version, key.encoded().to_vec().into_pyobject(py)?)?;
            }
            outer.set_item("keys", keys_dict)?;

            // Set latest_version
            match result.latest_version {
                Some(v) => outer.set_item("latest_version", v)?,
                None => outer.set_item("latest_version", py.None())?,
            }

            Ok(outer.into())
        })
    }

    /// Decrypt multiple events in batch.
    ///
    /// This is the recommended API for decrypting events. It:
    /// 1. Extracts conversation keys from any KeyChange events
    /// 2. For each event, finds the correct signing key by matching user_id + version
    /// 3. Decrypts the event using the appropriate conversation key
    ///
    /// Args:
    ///     events: List of base64-encoded raw event strings from webhook.
    ///     signing_keys: List of dicts ``{"user_id": str, "public_key_version": str, "public_key": str,
    ///         "identity_public_key": str, "identity_public_key_signature": str}`` for ALL participants,
    ///         straight from the X API public keys response. The SDK matches by user_id and version
    ///         automatically and verifies each key's identity binding. When omitted (or empty),
    ///         the keys stored via ``set_signing_keys`` are used.
    ///
    /// Returns:
    ///     A dict with:
    ///     - ``messages``: List of ``{"event": dict, "original_b64": str}``
    ///     - ``conversation_keys``: ``{"keys": dict, "latest_version": str}``
    ///     - ``errors``: Dict mapping event index (string, e.g. ``"0"``) to error message
    #[pyo3(signature = (events, signing_keys=None))]
    fn decrypt_events(
        &self,
        py: Python<'_>,
        events: Vec<String>,
        signing_keys: Option<Vec<std::collections::HashMap<String, String>>>,
    ) -> PyResult<Py<PyAny>> {
        let refs: Vec<&str> = events.iter().map(|s| s.as_str()).collect();

        let signing: Vec<chat_xdk_core::SigningKeyEntry> = signing_keys
            .unwrap_or_default()
            .into_iter()
            .map(parse_signing_key_entry)
            .collect::<PyResult<Vec<_>>>()?;

        // Release the GIL for the batch crypto so other Python threads keep
        // running; only Rust data crosses into the closure.
        let result = py.detach(|| self.inner.decrypt_events(&refs, &signing));

        Python::attach(|py| {
            let outer = pyo3::types::PyDict::new(py);

            // Convert messages
            let messages = pyo3::types::PyList::empty(py);
            let json_module = py.import("json")?;
            for dm in result.messages {
                let msg_dict = pyo3::types::PyDict::new(py);
                let event_json = serde_json::to_string(&dm.event).map_err(to_py_err)?;
                let event_dict = json_module.call_method1("loads", (event_json,))?;
                msg_dict.set_item("event", event_dict)?;
                if let Some(b64) = dm.original_b64 {
                    msg_dict.set_item("original_b64", b64)?;
                }
                messages.append(msg_dict)?;
            }
            outer.set_item("messages", messages)?;

            // Convert conversation keys
            let conv_keys_dict = pyo3::types::PyDict::new(py);
            let keys_dict = pyo3::types::PyDict::new(py);
            for (version, key) in result.conversation_keys.keys {
                keys_dict.set_item(version, key.encoded().to_vec().into_pyobject(py)?)?;
            }
            conv_keys_dict.set_item("keys", keys_dict)?;
            match result.conversation_keys.latest_version {
                Some(v) => conv_keys_dict.set_item("latest_version", v)?,
                None => conv_keys_dict.set_item("latest_version", py.None())?,
            }
            outer.set_item("conversation_keys", conv_keys_dict)?;

            // Convert errors; keys are the stringified event indices.
            let errors_dict = pyo3::types::PyDict::new(py);
            for (idx, err) in result.errors {
                errors_dict.set_item(idx.to_string(), err)?;
            }
            outer.set_item("errors", errors_dict)?;

            Ok(outer.into())
        })
    }

    /// Decrypt a raw webhook event payload.
    ///
    /// Args:
    ///     event_b64: Base64-encoded event from webhook.
    ///     conversation_keys: Dict mapping key version to raw 32-byte key (``bytes``),
    ///         from ``extract_conversation_keys()["keys"]``. When omitted (or empty), the
    ///         opt-in ``set_cache_keys`` cache is consulted instead.
    ///     signing_keys: List of dicts ``{"user_id": str, "public_key_version": str, "public_key": str,
    ///         "identity_public_key": str, "identity_public_key_signature": str}`` for the sender,
    ///         straight from the X API public keys response. The SDK picks the matching version
    ///         automatically. When omitted (or empty), the keys stored via ``set_signing_keys``
    ///         are used. Under the default reject-unverified policy no usable signing key makes
    ///         every signed event raise; only after ``set_reject_unverified(False)`` are such
    ///         events returned with ``verified: False``.
    ///
    /// Returns:
    ///     A dictionary representing the decrypted event.
    #[pyo3(signature = (event_b64, conversation_keys=None, signing_keys=None))]
    fn decrypt_event(
        &self,
        event_b64: &str,
        conversation_keys: Option<std::collections::HashMap<String, Vec<u8>>>,
        signing_keys: Option<Vec<std::collections::HashMap<String, String>>>,
    ) -> PyResult<Py<PyAny>> {
        use chat_xdk_core::crypto::keys::XChatConversationKey;

        let conv_keys: std::collections::HashMap<String, XChatConversationKey> = conversation_keys
            .unwrap_or_default()
            .into_iter()
            .filter_map(|(k, v)| XChatConversationKey::from_bytes(v).map(|ck| (k, ck)))
            .collect();

        let signing: Vec<chat_xdk_core::SigningKeyEntry> = signing_keys
            .unwrap_or_default()
            .into_iter()
            .map(parse_signing_key_entry)
            .collect::<PyResult<Vec<_>>>()?;

        let event = self
            .inner
            .decrypt_event(event_b64, &conv_keys, &signing)
            .map_err(to_py_err)?;

        let json_str = serde_json::to_string(&event).map_err(to_py_err)?;

        Python::attach(|py| {
            let json_module = py.import("json")?;
            let dict = json_module.call_method1("loads", (json_str,))?;
            Ok(dict.into())
        })
    }

    /// Encrypt a message for the X API.
    ///
    /// The SDK generates the message id and returns it in the payload; read it
    /// back from ``payload.message_id`` (do not pass one in).
    ///
    /// Args:
    ///     conversation_id: The conversation ID.
    ///     text: Plaintext message.
    ///     sender_id: Your user ID; defaults to the ``set_identity`` value.
    ///         Keyword-only, like every optional argument below it.
    ///     signing_key_version: Your registered signing public key version;
    ///         defaults to the ``set_identity`` value.
    ///     conversation_key: Raw 32-byte conversation key (``bytes``), from
    ///         decrypt_conversation_key() or a prepared key change. Pass it
    ///         together with ``conversation_key_version``, or omit both to
    ///         resolve from the opt-in ``set_cache_keys`` cache.
    ///     conversation_key_version: The current conversation key version (from KeyChange event).
    ///     entities: Optional list of (start, end, entity_type) tuples for rich-text.
    ///     attachments: Optional list of attachment dicts (each with "attachment_type" key).
    ///     should_notify: Whether to send a push notification (default: True).
    ///     ttl_msec: Optional TTL in milliseconds for disappearing messages.
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (conversation_id, text, *, sender_id=None, signing_key_version=None, conversation_key=None, conversation_key_version=None, entities=None, attachments=None, should_notify=None, ttl_msec=None))]
    fn encrypt_message(
        &self,
        conversation_id: &str,
        text: &str,
        sender_id: Option<String>,
        signing_key_version: Option<String>,
        conversation_key: Option<Vec<u8>>,
        conversation_key_version: Option<String>,
        entities: Option<Vec<(i32, i32, String)>>,
        attachments: Option<Vec<HashMap<String, Py<PyAny>>>>,
        should_notify: Option<bool>,
        ttl_msec: Option<i64>,
    ) -> PyResult<SendPayload> {
        let mut params = EncryptMessageParams::new(conversation_id, text);
        params.sender_id = sender_id;
        params.signing_key_version = signing_key_version;
        params.conversation_key = conversation_key;
        params.conversation_key_version = conversation_key_version;
        params.entities = entities.map(parse_entity_descs);
        params.attachments = attachments.map(parse_attachment_descs).transpose()?;
        params.should_notify = should_notify;
        params.ttl_msec = ttl_msec;
        let payload = self.inner.encrypt_message(params).map_err(to_py_err)?;

        Ok(to_py_send_payload(payload))
    }

    /// Encrypt a reply message for the X API.
    ///
    /// Like encrypt_message but populates the replying_to_preview so the
    /// receiving client renders it as a reply to an existing message. The
    /// preferred form passes ``reply_to_event`` — the base64 raw signed event
    /// being replied to — so the preview (sequence id, sender, text,
    /// entities, attachments) is derived from it and the raw event is
    /// embedded for recipients to validate. The ``reply_to_*`` overrides
    /// remain for callers that no longer hold the raw event.
    ///
    /// The SDK generates the message id and returns it in the payload; read it
    /// back from ``payload.message_id`` (do not pass one in).
    ///
    /// Args:
    ///     conversation_id: The conversation ID.
    ///     text: Plaintext message.
    ///     reply_to_event: Base64 raw signed event being replied to. Omit it
    ///         only when supplying ``reply_to_sequence_id`` directly.
    ///     reply_to_edit_event: Base64 raw signed edit event, when the
    ///         original was edited. Keyword-only, like every optional
    ///         argument below it.
    ///     reply_to_ckces: Base64 raw key-change events needed to decrypt the
    ///         original when it used a different key version than this reply.
    ///     reply_to_sequence_id: The sequence_id of the message being replied
    ///         to; derived from ``reply_to_event`` when omitted.
    ///     reply_to_sender_id: Sender ID of the message being replied to;
    ///         derived from ``reply_to_event`` when omitted.
    ///     reply_to_text: Text of the message being replied to (for preview);
    ///         derived from ``reply_to_event`` when omitted.
    ///     reply_to_entities: (start, end, entity_type) tuples for rich-text
    ///         in the replied-to preview; derived from ``reply_to_event``
    ///         when omitted.
    ///     reply_to_attachments: Attachment dicts describing the replied-to
    ///         message's attachments (for preview); derived from
    ///         ``reply_to_event`` when omitted.
    ///     sender_id: Your user ID; defaults to the ``set_identity`` value.
    ///     signing_key_version: Your registered signing public key version;
    ///         defaults to the ``set_identity`` value.
    ///     conversation_key: Raw 32-byte conversation key (``bytes``). Pass it
    ///         together with ``conversation_key_version``, or omit both to
    ///         resolve from the opt-in ``set_cache_keys`` cache.
    ///     conversation_key_version: The current conversation key version.
    ///     entities: Optional list of (start, end, entity_type) tuples for
    ///         rich-text in the reply text.
    ///     attachments: Optional list of attachment dicts (each with "attachment_type" key).
    ///     should_notify: Whether to send a push notification (default: True).
    ///     ttl_msec: Optional TTL in milliseconds for disappearing messages.
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (conversation_id, text, reply_to_event=None, *, reply_to_edit_event=None, reply_to_ckces=None, reply_to_sequence_id=None, reply_to_sender_id=None, reply_to_text=None, reply_to_entities=None, reply_to_attachments=None, sender_id=None, signing_key_version=None, conversation_key=None, conversation_key_version=None, entities=None, attachments=None, should_notify=None, ttl_msec=None))]
    fn encrypt_reply(
        &self,
        conversation_id: &str,
        text: &str,
        reply_to_event: Option<String>,
        reply_to_edit_event: Option<String>,
        reply_to_ckces: Option<Vec<String>>,
        reply_to_sequence_id: Option<String>,
        reply_to_sender_id: Option<i64>,
        reply_to_text: Option<String>,
        reply_to_entities: Option<Vec<(i32, i32, String)>>,
        reply_to_attachments: Option<Vec<HashMap<String, Py<PyAny>>>>,
        sender_id: Option<String>,
        signing_key_version: Option<String>,
        conversation_key: Option<Vec<u8>>,
        conversation_key_version: Option<String>,
        entities: Option<Vec<(i32, i32, String)>>,
        attachments: Option<Vec<HashMap<String, Py<PyAny>>>>,
        should_notify: Option<bool>,
        ttl_msec: Option<i64>,
    ) -> PyResult<SendPayload> {
        let mut params =
            EncryptReplyParams::new(conversation_id, text, reply_to_event.unwrap_or_default());
        params.reply_to_edit_event = reply_to_edit_event;
        params.reply_to_ckces = reply_to_ckces;
        params.reply_to_sequence_id = reply_to_sequence_id;
        params.reply_to_sender_id = reply_to_sender_id;
        params.reply_to_text = reply_to_text;
        params.reply_to_entities = reply_to_entities.map(parse_entity_descs);
        params.reply_to_attachments = reply_to_attachments
            .map(parse_attachment_descs)
            .transpose()?;
        params.sender_id = sender_id;
        params.signing_key_version = signing_key_version;
        params.conversation_key = conversation_key;
        params.conversation_key_version = conversation_key_version;
        params.entities = entities.map(parse_entity_descs);
        params.attachments = attachments.map(parse_attachment_descs).transpose()?;
        params.should_notify = should_notify;
        params.ttl_msec = ttl_msec;
        let payload = self.inner.encrypt_reply(params).map_err(to_py_err)?;

        Ok(to_py_send_payload(payload))
    }

    /// Encrypt a reaction-add for the X API.
    ///
    /// The preferred form passes ``target_event`` — the base64 raw event
    /// being reacted to — so the conversation id and target sequence id are
    /// derived from it. The explicit overrides remain for callers that no
    /// longer hold the raw event.
    ///
    /// The SDK generates the message id and returns it in the payload; read it
    /// back from ``payload.message_id`` (do not pass one in).
    ///
    /// Args:
    ///     target_event: Base64 raw event being reacted to. Omit it only when
    ///         supplying ``conversation_id`` and ``target_message_sequence_id``.
    ///     emoji: Emoji to add.
    ///     conversation_id: The conversation ID; derived from ``target_event``
    ///         when omitted. Keyword-only, like every optional argument below it.
    ///     target_message_sequence_id: Message sequence ID being reacted to;
    ///         derived from ``target_event`` when omitted.
    ///     sender_id: Your user ID; defaults to the ``set_identity`` value.
    ///     signing_key_version: Your registered signing public key version;
    ///         defaults to the ``set_identity`` value.
    ///     conversation_key: Raw 32-byte conversation key (``bytes``). Pass it
    ///         together with ``conversation_key_version``, or omit both to
    ///         resolve from the opt-in ``set_cache_keys`` cache.
    ///     conversation_key_version: Current conversation key version.
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (target_event=None, emoji=None, *, conversation_id=None, target_message_sequence_id=None, sender_id=None, signing_key_version=None, conversation_key=None, conversation_key_version=None))]
    fn encrypt_add_reaction(
        &self,
        target_event: Option<String>,
        emoji: Option<String>,
        conversation_id: Option<String>,
        target_message_sequence_id: Option<String>,
        sender_id: Option<String>,
        signing_key_version: Option<String>,
        conversation_key: Option<Vec<u8>>,
        conversation_key_version: Option<String>,
    ) -> PyResult<SendPayload> {
        let params = build_reaction_params(
            target_event,
            emoji,
            conversation_id,
            target_message_sequence_id,
            sender_id,
            signing_key_version,
            conversation_key,
            conversation_key_version,
        )?;
        let payload = self
            .inner
            .encrypt_add_reaction(&params)
            .map_err(to_py_err)?;

        Ok(to_py_send_payload(payload))
    }

    /// Encrypt a reaction-remove for the X API.
    ///
    /// Takes the same arguments as ``encrypt_add_reaction`` — pass the same
    /// values to remove a previously added reaction.
    ///
    /// The SDK generates the message id and returns it in the payload; read it
    /// back from ``payload.message_id`` (do not pass one in).
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (target_event=None, emoji=None, *, conversation_id=None, target_message_sequence_id=None, sender_id=None, signing_key_version=None, conversation_key=None, conversation_key_version=None))]
    fn encrypt_remove_reaction(
        &self,
        target_event: Option<String>,
        emoji: Option<String>,
        conversation_id: Option<String>,
        target_message_sequence_id: Option<String>,
        sender_id: Option<String>,
        signing_key_version: Option<String>,
        conversation_key: Option<Vec<u8>>,
        conversation_key_version: Option<String>,
    ) -> PyResult<SendPayload> {
        let params = build_reaction_params(
            target_event,
            emoji,
            conversation_id,
            target_message_sequence_id,
            sender_id,
            signing_key_version,
            conversation_key,
            conversation_key_version,
        )?;
        let payload = self
            .inner
            .encrypt_remove_reaction(&params)
            .map_err(to_py_err)?;

        Ok(to_py_send_payload(payload))
    }

    /// Decrypt an encrypted conversation key (ECIES).
    ///
    /// Call this once per key version, then pass the result to ``decrypt_event()``.
    ///
    /// Args:
    ///     encrypted_key_b64: Base64-encoded **encrypted** key from KeyChange event.
    ///
    /// Returns:
    ///     Raw 32-byte decrypted conversation key as ``bytes``.
    fn decrypt_conversation_key<'py>(
        &self,
        py: Python<'py>,
        encrypted_key_b64: &str,
    ) -> PyResult<Bound<'py, PyBytes>> {
        let ckey = self
            .inner
            .decrypt_conversation_key(encrypted_key_b64)
            .map_err(to_py_err)?;
        Ok(PyBytes::new(py, ckey.encoded()))
    }

    /// Encrypt a stream (e.g. media) with a conversation key.
    ///
    /// Args:
    ///     plaintext: Raw bytes to encrypt.
    ///     conversation_key: Raw 32-byte conversation key (``bytes``),
    ///         from ``decrypt_conversation_key()`` or a prepared key change.
    ///
    /// Returns:
    ///     Encrypted bytes.
    fn encrypt_stream(&self, plaintext: &[u8], conversation_key: &[u8]) -> PyResult<Py<PyAny>> {
        let ckey = chat_xdk_core::crypto::keys::XChatConversationKey::from_bytes(
            conversation_key.to_vec(),
        )
        .ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(
                "Invalid conversation key (expected 32 bytes)",
            )
        })?;

        let mut reader = Cursor::new(plaintext);
        let mut output: Vec<u8> = Vec::new();
        chat_xdk_core::crypto::encryption::encrypt_stream(&ckey, &mut reader, &mut output)
            .map_err(to_py_err)?;

        Python::attach(|py| Ok(PyBytes::new(py, &output).into()))
    }

    /// Decrypt a streaming-encrypted payload (e.g. media).
    ///
    /// Args:
    ///     encrypted: Raw encrypted bytes.
    ///     conversation_key: Raw 32-byte conversation key (``bytes``),
    ///         from ``decrypt_conversation_key()``.
    ///
    /// Returns:
    ///     Decrypted bytes.
    fn decrypt_stream(&self, encrypted: &[u8], conversation_key: &[u8]) -> PyResult<Py<PyAny>> {
        let ckey = chat_xdk_core::crypto::keys::XChatConversationKey::from_bytes(
            conversation_key.to_vec(),
        )
        .ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(
                "Invalid conversation key (expected 32 bytes)",
            )
        })?;

        let mut reader = Cursor::new(encrypted);
        let mut output: Vec<u8> = Vec::new();
        chat_xdk_core::crypto::encryption::decrypt_stream(&ckey, &mut reader, &mut output)
            .map_err(to_py_err)?;

        Python::attach(|py| Ok(PyBytes::new(py, &output).into()))
    }

    /// Create an incremental stream encryptor for large payloads.
    fn stream_encryptor(&self, conversation_key: &[u8]) -> PyResult<StreamEncryptor> {
        let ckey = chat_xdk_core::crypto::keys::XChatConversationKey::from_bytes(
            conversation_key.to_vec(),
        )
        .ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(
                "Invalid conversation key (expected 32 bytes)",
            )
        })?;
        let inner = self.inner.stream_encryptor(&ckey).map_err(to_py_err)?;
        Ok(StreamEncryptor { inner: Some(inner) })
    }

    /// Create an incremental stream decryptor for large payloads.
    fn stream_decryptor(&self, conversation_key: &[u8]) -> PyResult<StreamDecryptor> {
        let ckey = chat_xdk_core::crypto::keys::XChatConversationKey::from_bytes(
            conversation_key.to_vec(),
        )
        .ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(
                "Invalid conversation key (expected 32 bytes)",
            )
        })?;
        let inner = self.inner.stream_decryptor(&ckey).map_err(to_py_err)?;
        Ok(StreamDecryptor { inner: Some(inner) })
    }

    /// Encrypt a UTF-8 string and return base64 ciphertext.
    ///
    /// Use for metadata fields like group names before sending to the API.
    ///
    /// Args:
    ///     plaintext: The UTF-8 string to encrypt.
    ///     conversation_key: Raw 32-byte conversation key (``bytes``).
    ///
    /// Returns:
    ///     Base64-encoded ciphertext (``str``).
    fn encrypt(&self, plaintext: &str, conversation_key: &[u8]) -> PyResult<String> {
        let ckey = chat_xdk_core::crypto::keys::XChatConversationKey::from_bytes(
            conversation_key.to_vec(),
        )
        .ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(
                "Invalid conversation key (expected 32 bytes)",
            )
        })?;
        self.inner.encrypt(plaintext, &ckey).map_err(to_py_err)
    }

    /// Decrypt a base64-encoded ciphertext and return the UTF-8 plaintext.
    ///
    /// Use for metadata fields like group names returned by the API.
    ///
    /// Args:
    ///     ciphertext_b64: Base64-encoded ciphertext (``str``).
    ///     conversation_key: Raw 32-byte conversation key (``bytes``).
    ///
    /// Returns:
    ///     Decrypted UTF-8 string (``str``).
    fn decrypt(&self, ciphertext_b64: &str, conversation_key: &[u8]) -> PyResult<String> {
        let ckey = chat_xdk_core::crypto::keys::XChatConversationKey::from_bytes(
            conversation_key.to_vec(),
        )
        .ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyValueError, _>(
                "Invalid conversation key (expected 32 bytes)",
            )
        })?;
        self.inner.decrypt(ciphertext_b64, &ckey).map_err(to_py_err)
    }

    /// Prepare a signed conversation-key change, ready to send to the X API.
    ///
    /// Use this to start a one-to-one or rotate an existing conversation's key
    /// (one-to-one or group). Creating a group or adding members requires a
    /// paired group signature as well — use ``prepare_group_create`` or
    /// ``prepare_group_members_change`` for those.
    ///
    /// Generates a fresh conversation key, encrypts it for every participant,
    /// and signs the change. Omit ``conversation_id`` for a one-to-one (it is
    /// derived from the two participants); pass the existing id for a group
    /// key rotation.
    ///
    /// Args:
    ///     public_keys: List of dicts with ``user_id``, ``public_key``, ``key_version``.
    ///     conversation_id: Optional; omit for a one-to-one to derive it. Keyword-only,
    ///         like every optional argument below it.
    ///     sender_id: The local user's id; defaults to the ``set_identity`` value.
    ///     signing_key_version: Version of the local signing key; defaults to
    ///         the ``set_identity`` value.
    ///
    /// Returns:
    ///     A dict with ``conversation_id``, ``conversation_key`` (bytes),
    ///     ``conversation_key_version``, ``participant_keys``, ``action_signatures``.
    #[pyo3(signature = (public_keys, *, conversation_id=None, sender_id=None, signing_key_version=None))]
    fn prepare_conversation_key_change(
        &self,
        public_keys: Vec<std::collections::HashMap<String, String>>,
        conversation_id: Option<String>,
        sender_id: Option<String>,
        signing_key_version: Option<String>,
    ) -> PyResult<Py<PyAny>> {
        let mut params = ConversationKeyChangeParams::new(parse_public_key_inputs(public_keys)?);
        params.conversation_id = conversation_id;
        params.sender_id = sender_id;
        params.signing_key_version = signing_key_version;
        let result = self
            .inner
            .prepare_conversation_key_change(params)
            .map_err(to_py_err)?;
        Python::attach(|py| prepared_change_to_pydict(py, &result))
    }

    /// Prepare a signed group member-add change, ready to send to the X API.
    ///
    /// Use this when adding members to an existing group. Creating the group
    /// is ``prepare_group_create``; a key rotation without a roster change is
    /// ``prepare_conversation_key_change``.
    ///
    /// Args:
    ///     public_keys: List of dicts with ``user_id``, ``public_key``, ``key_version`` for the roster.
    ///     conversation_id: The group conversation id.
    ///     new_member_ids / current_member_ids / current_admin_ids / current_pending_member_ids: Roster ids.
    ///     sender_id: The local user's id; defaults to the ``set_identity``
    ///         value. Keyword-only, like every optional argument below it.
    ///     signing_key_version: Version of the local signing key; defaults to
    ///         the ``set_identity`` value.
    ///     current_title / current_avatar_url / current_ttl_msec: Optional group settings.
    ///     current_screen_capture_blocking_enabled: The group's current
    ///         screen-capture-blocking state; leave ``None`` when unset.
    ///
    /// Returns:
    ///     The same dict shape as ``prepare_conversation_key_change``, with
    ///     two action signatures: the conversation-key change and the
    ///     member add.
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (public_keys, conversation_id, new_member_ids, current_member_ids, current_admin_ids, current_pending_member_ids, *, sender_id=None, signing_key_version=None, current_title=None, current_avatar_url=None, current_ttl_msec=None, current_screen_capture_blocking_enabled=None))]
    fn prepare_group_members_change(
        &self,
        public_keys: Vec<std::collections::HashMap<String, String>>,
        conversation_id: &str,
        new_member_ids: Vec<String>,
        current_member_ids: Vec<String>,
        current_admin_ids: Vec<String>,
        current_pending_member_ids: Vec<String>,
        sender_id: Option<String>,
        signing_key_version: Option<String>,
        current_title: Option<String>,
        current_avatar_url: Option<String>,
        current_ttl_msec: Option<i64>,
        current_screen_capture_blocking_enabled: Option<bool>,
    ) -> PyResult<Py<PyAny>> {
        let mut params = GroupMembersChangeParams::new(
            parse_public_key_inputs(public_keys)?,
            conversation_id,
            new_member_ids,
            current_member_ids,
            current_admin_ids,
            current_pending_member_ids,
        );
        params.sender_id = sender_id;
        params.signing_key_version = signing_key_version;
        params.current_title = current_title;
        params.current_avatar_url = current_avatar_url;
        params.current_ttl_msec = current_ttl_msec;
        params.current_screen_capture_blocking_enabled = current_screen_capture_blocking_enabled;
        let result = self
            .inner
            .prepare_group_members_change(params)
            .map_err(to_py_err)?;
        Python::attach(|py| prepared_change_to_pydict(py, &result))
    }

    /// Prepare a signed group create, ready to send to the X API.
    ///
    /// Use this once, when creating a group (``conversation_id`` is the
    /// g-prefixed id minted by the initialize endpoint). Later key rotations
    /// use ``prepare_conversation_key_change``; roster additions use
    /// ``prepare_group_members_change``.
    ///
    /// Args:
    ///     public_keys: List of dicts with ``user_id``, ``public_key``, ``key_version`` for the roster.
    ///     conversation_id: The group conversation id.
    ///     member_ids / admin_ids: Roster ids for the new group.
    ///     sender_id: The local user's id; defaults to the ``set_identity``
    ///         value. Keyword-only, like every optional argument below it.
    ///     signing_key_version: Version of the local signing key; defaults to
    ///         the ``set_identity`` value.
    ///     title / avatar_url / ttl_msec: Optional group settings.
    ///
    /// Returns:
    ///     The same dict shape as ``prepare_conversation_key_change``, with
    ///     two action signatures: the conversation-key change and the
    ///     group create.
    #[allow(clippy::too_many_arguments)]
    #[pyo3(signature = (public_keys, conversation_id, member_ids, admin_ids, *, sender_id=None, signing_key_version=None, title=None, avatar_url=None, ttl_msec=None))]
    fn prepare_group_create(
        &self,
        public_keys: Vec<std::collections::HashMap<String, String>>,
        conversation_id: &str,
        member_ids: Vec<String>,
        admin_ids: Vec<String>,
        sender_id: Option<String>,
        signing_key_version: Option<String>,
        title: Option<String>,
        avatar_url: Option<String>,
        ttl_msec: Option<i64>,
    ) -> PyResult<Py<PyAny>> {
        let mut params = GroupCreateParams::new(
            parse_public_key_inputs(public_keys)?,
            conversation_id,
            member_ids,
            admin_ids,
        );
        params.sender_id = sender_id;
        params.signing_key_version = signing_key_version;
        params.title = title;
        params.avatar_url = avatar_url;
        params.ttl_msec = ttl_msec;
        let result = self.inner.prepare_group_create(params).map_err(to_py_err)?;
        Python::attach(|py| prepared_change_to_pydict(py, &result))
    }

    /// Export private keys as raw bytes for secure storage.
    ///
    /// Warning: Handle with care — these are your secret keys!
    ///
    /// Returns a mutable ``bytearray`` so the caller can zero it after
    /// use (e.g. ``buf[:] = b"\x00" * len(buf)``); an immutable ``bytes``
    /// object could linger in memory until garbage collection.
    ///
    /// Returns:
    ///     Raw key bytes (32 or 64 bytes) as bytearray, or None if no
    ///     identity key is loaded.
    fn export_keys<'py>(&self, py: Python<'py>) -> PyResult<Option<Bound<'py, PyByteArray>>> {
        // Mirror core's export requirement: identity key present (signing
        // key optional, giving a 32-byte export).
        if !self.inner.has_identity_key() {
            return Ok(None);
        }
        use zeroize::Zeroize;
        let mut key_bytes = self.inner.export_keys().map_err(to_py_err)?;
        let out = PyByteArray::new(py, &key_bytes);
        key_bytes.zeroize();
        Ok(Some(out))
    }

    /// Import private keys from raw bytes.
    ///
    /// Accepts 32 bytes (identity only) or 64 bytes (identity + signing).
    ///
    /// Args:
    ///     keys: Raw key bytes from ``export_keys()``.
    ///     version: Optional public key version the keys were registered
    ///         under; when given, participant-key filtering by version is
    ///         enabled in the same call.
    #[pyo3(signature = (keys, version=None))]
    fn import_keys(&self, keys: &[u8], version: Option<&str>) -> PyResult<()> {
        match version {
            Some(v) => self
                .inner
                .import_keys_with_version(keys, v)
                .map_err(to_py_err),
            None => self.inner.import_keys(keys).map_err(to_py_err),
        }
    }

    /// Sign arbitrary data. Returns raw signature bytes.
    ///
    /// Args:
    ///     data: Bytes to sign.
    ///
    /// Returns:
    ///     Raw signature bytes (64 bytes).
    fn sign<'py>(&self, py: Python<'py>, data: &[u8]) -> PyResult<Bound<'py, PyBytes>> {
        let sig = self.inner.sign(data).map_err(to_py_err)?;
        Ok(PyBytes::new(py, &sig))
    }

    /// Verify a signature.
    ///
    /// Args:
    ///     public_key_b64: Base64-encoded public key.
    ///     signature: Raw signature bytes.
    ///     data: The signed data.
    ///
    /// Returns:
    ///     True if signature is valid.
    fn verify(&self, public_key_b64: &str, signature: &[u8], data: &[u8]) -> PyResult<bool> {
        self.inner
            .verify(public_key_b64, signature, data)
            .map_err(to_py_err)
    }

    /// Verify that a signing key is authentically bound to an identity key.
    ///
    /// Call this when you receive another user's public keys from the X API
    /// to detect server-side key substitution.
    ///
    /// Args:
    ///     identity_public_key_b64: Base64 SPKI identity public key.
    ///     signing_public_key_b64: Base64 SPKI signing public key.
    ///     identity_public_key_signature_b64: Base64 raw r||s signature.
    ///
    /// Returns:
    ///     True if the binding is valid.
    fn verify_key_binding(
        &self,
        identity_public_key_b64: &str,
        signing_public_key_b64: &str,
        identity_public_key_signature_b64: &str,
    ) -> PyResult<bool> {
        self.inner
            .verify_key_binding(
                identity_public_key_b64,
                signing_public_key_b64,
                identity_public_key_signature_b64,
            )
            .map_err(to_py_err)
    }

    /// Report whether the loaded identity public key is the key in
    /// `public_key_b64`.
    ///
    /// The X API returns the identity public key in SPKI/DER encoding while
    /// `get_public_keys` returns the raw SEC1 point; this accepts either
    /// encoding, so use it to check whether the keys on this device belong
    /// to a key registered to the account.
    ///
    /// Args:
    ///     public_key_b64: Base64 public key, raw SEC1 point or SPKI/DER.
    ///
    /// Returns:
    ///     True if it is the loaded identity public key.
    fn matches_registered_key(&self, public_key_b64: &str) -> PyResult<bool> {
        self.inner
            .matches_registered_key(public_key_b64)
            .map_err(to_py_err)
    }
}

// Module-level utility functions

/// Encode bytes to base64 string.
#[pyfunction]
fn bytes_to_base64(bytes: &[u8]) -> String {
    chat_xdk_core::utils::bytes_to_base64(bytes)
}

/// Decode base64 string to bytes.
///
/// Returns None if the input is not valid base64.
#[pyfunction]
fn base64_to_bytes<'py>(py: Python<'py>, b64: &str) -> Option<Bound<'py, PyBytes>> {
    chat_xdk_core::utils::base64_to_bytes(b64).map(|bytes| PyBytes::new(py, &bytes))
}

/// Encode bytes to lowercase hex string.
#[pyfunction]
fn bytes_to_hex(bytes: &[u8]) -> String {
    chat_xdk_core::utils::bytes_to_hex(bytes)
}

/// Decode hex string to bytes.
///
/// Returns None if the input is not valid hex.
#[pyfunction]
fn hex_to_bytes<'py>(py: Python<'py>, hex: &str) -> Option<Bound<'py, PyBytes>> {
    chat_xdk_core::utils::hex_to_bytes(hex).map(|bytes| PyBytes::new(py, &bytes))
}

/// Detect MIME type from file bytes using magic numbers.
///
/// Returns the MIME type string (e.g., "image/png", "video/mp4") or None.
#[pyfunction]
fn detect_mime_type(bytes: &[u8]) -> Option<&'static str> {
    chat_xdk_core::utils::detect_mime_type(bytes)
}

/// Detect image dimensions from file bytes.
///
/// Supports PNG, JPEG, GIF, WebP, and BMP.
/// Returns a tuple (width, height) or None.
#[pyfunction]
fn detect_image_dimensions(bytes: &[u8]) -> Option<(u32, u32)> {
    chat_xdk_core::utils::detect_image_dimensions(bytes).map(|d| (d.width, d.height))
}

/// Incremental stream encryptor for large payloads.
///
/// Feed plaintext with ``push``; call ``finish`` once to emit the final frame.
#[pyclass]
pub struct StreamEncryptor {
    inner: Option<chat_xdk_core::StreamEncryptor>,
}

#[pymethods]
impl StreamEncryptor {
    /// Encrypt a plaintext chunk, returning ciphertext available so far.
    fn push(&mut self, plaintext: &[u8]) -> PyResult<Py<PyAny>> {
        let enc = self.inner.as_mut().ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyRuntimeError, _>("stream encryptor already finished")
        })?;
        let out = enc.push(plaintext).map_err(to_py_err)?;
        Python::attach(|py| Ok(PyBytes::new(py, &out).into()))
    }

    /// Emit the final frame and consume the encryptor.
    fn finish(&mut self) -> PyResult<Py<PyAny>> {
        let enc = self.inner.take().ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyRuntimeError, _>("stream encryptor already finished")
        })?;
        let out = enc.finish().map_err(to_py_err)?;
        Python::attach(|py| Ok(PyBytes::new(py, &out).into()))
    }
}

/// Incremental stream decryptor for large payloads.
///
/// Feed ciphertext with ``push``; call ``finish`` once at end of input.
/// ``finish`` raises if the stream ended before its final frame (truncation),
/// so callers must not treat plaintext from ``push`` as complete until
/// ``finish`` succeeds.
#[pyclass]
pub struct StreamDecryptor {
    inner: Option<chat_xdk_core::StreamDecryptor>,
}

#[pymethods]
impl StreamDecryptor {
    /// Decrypt a ciphertext chunk, returning plaintext available so far.
    fn push(&mut self, ciphertext: &[u8]) -> PyResult<Py<PyAny>> {
        let dec = self.inner.as_mut().ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyRuntimeError, _>("stream decryptor already finished")
        })?;
        let out = dec.push(ciphertext).map_err(to_py_err)?;
        Python::attach(|py| Ok(PyBytes::new(py, &out).into()))
    }

    /// Decrypt the final frame and consume the decryptor.
    fn finish(&mut self) -> PyResult<Py<PyAny>> {
        let dec = self.inner.take().ok_or_else(|| {
            PyErr::new::<pyo3::exceptions::PyRuntimeError, _>("stream decryptor already finished")
        })?;
        let out = dec.finish().map_err(to_py_err)?;
        Python::attach(|py| Ok(PyBytes::new(py, &out).into()))
    }
}

#[pymodule]
fn _native(m: &Bound<'_, pyo3::types::PyModule>) -> PyResult<()> {
    m.add_class::<Chat>()?;
    m.add_class::<StreamEncryptor>()?;
    m.add_class::<StreamDecryptor>()?;
    m.add_class::<PublicKeyRegistrationPayload>()?;
    m.add_class::<PublicKeyRegistration>()?;
    m.add_class::<PublicKeys>()?;
    m.add_class::<SendPayload>()?;
    m.add_class::<SignatureInfo>()?;

    // Utility functions
    m.add_function(wrap_pyfunction!(bytes_to_base64, m)?)?;
    m.add_function(wrap_pyfunction!(base64_to_bytes, m)?)?;
    m.add_function(wrap_pyfunction!(bytes_to_hex, m)?)?;
    m.add_function(wrap_pyfunction!(hex_to_bytes, m)?)?;
    m.add_function(wrap_pyfunction!(detect_mime_type, m)?)?;
    m.add_function(wrap_pyfunction!(detect_image_dimensions, m)?)?;

    Ok(())
}
